<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { approveExtensionByAdmin, getExtensionRequest, rejectExtensionByAdmin } from '../api/applicationApi.js'
import { adaptExtensionRequest } from '../adapters/applicationAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const route=useRoute();const router=useRouter();const comment=ref('');const item=ref(null)
const pending=computed(()=>item.value?.actions?.can_approve===true||item.value?.actions?.can_reject===true||(item.value?.canOperate===true&&item.value?.status==='submitted')||item.value?.status==='submitted')
async function loadItem(){try{item.value=adaptExtensionRequest(await getExtensionRequest(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'特殊延期详情加载失败'))}}
onMounted(loadItem)
const extensionDays=computed(()=>item.value?Math.ceil((new Date(`${item.value.newExpectedResultTime}T00:00:00`)-new Date(`${item.value.originalExpectedResultTime}T00:00:00`))/86400000):0)
function back(){router.push('/admin/extensions')}
function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}
function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
async function approve(){if(!pending.value)return window.alert('该特殊延期申请已处理。');try{await approveExtensionByAdmin(item.value.id,{comment:comment.value.trim()});await loadItem();window.alert('特殊延期已审核通过，学生可在新的截止时间前补交成果。');back()}catch(error){window.alert(getApiErrorMessage(error,'审核失败，请稍后重试'))}}
async function reject(){if(!comment.value.trim())return window.alert('驳回特殊延期时必须填写审核意见。');try{await rejectExtensionByAdmin(item.value.id,{comment:comment.value.trim()});await loadItem();window.alert('特殊延期已驳回。');back()}catch(error){window.alert(getApiErrorMessage(error,'驳回失败，请稍后重试'))}}
</script>
<template><main class="page"><div class="content"><template v-if="item"><header><div><p class="eyebrow">A702 · SPECIAL EXTENSION DETAIL</p><h1>特殊延期审核详情</h1><p>{{ item.id }}</p></div><StatusTag :status="item.status" /></header><section class="card"><h2>原课时申请</h2><dl class="grid"><div><dt>申请名称</dt><dd>{{ item.title }}</dd></div><div><dt>申请类型</dt><dd>{{ item.applyTypeText }}</dd></div><div><dt>申请课时</dt><dd>{{ item.requestedHours }} 课时</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="item.status" /></dd></div><div><dt>学生姓名</dt><dd>{{ item.studentName }}</dd></div><div><dt>学号</dt><dd>{{ item.studentId }}</dd></div><div><dt>主指导老师</dt><dd>{{ item.mainAdvisor?.name||'--' }}</dd></div><div><dt>延期提交时间</dt><dd>{{ item.extensionSubmitTime }}</dd></div></dl></section><section class="card"><h2>特殊延期内容</h2><dl class="grid"><div><dt>原预计成果提交时间</dt><dd>{{ item.originalExpectedResultTime }}</dd></div><div><dt>新预计成果提交时间</dt><dd>{{ item.newExpectedResultTime }}</dd></div><div><dt>延期天数</dt><dd>{{ extensionDays }} 天</dd></div><div class="wide"><dt>延期原因</dt><dd>{{ item.extensionReason }}</dd></div></dl></section><section class="card"><h2>延期证明材料</h2><div class="files"><article v-for="file in item.extensionMaterials" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!item.extensionMaterials?.length">暂无附件材料</p></div></section><section class="card"><h2>管理员审核意见</h2><textarea v-model="comment" rows="5" :disabled="!pending" placeholder="请输入审核意见；驳回时必填。"></textarea></section><div class="actions"><button @click="back">返回</button><button class="reject" :disabled="!pending" @click="reject">驳回延期</button><button class="approve" :disabled="!pending" @click="approve">审核通过</button></div></template><section v-else class="card empty">特殊延期申请不存在。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,920px);margin:auto}header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p{color:#64748b}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}.wide{grid-column:1/-1}dt{color:#64748b;font-size:13px}dd{margin:5px 0 0;font-weight:600;line-height:1.7}.files{display:grid;gap:10px}.files article{display:flex;justify-content:space-between;gap:14px;padding:13px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.files small{display:block;margin-top:5px;color:#64748b}.files article>div:last-child{display:flex;gap:8px}.files button,.actions button,.empty button{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff;font:inherit;font-weight:700}textarea{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button{padding:10px 18px}.actions .reject{color:#b91c1c;border-color:#fecaca}.actions .approve{border:0;color:#fff;background:#2563eb}.actions button:disabled{opacity:.5}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}header,.files article{flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.actions{flex-wrap:wrap}}</style>
