<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getAdminPendingSpecialExtensions } from '../api/applicationApi.js'
import { adaptExtensionList } from '../adapters/applicationAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const APPLICATION_STATUS={PENDING_ADMIN_SPECIAL_EXTENSION:'pending_admin_review'}
const keyword=ref('');const status=ref('pending_admin_review');const remoteItems=ref([])
async function loadItems(){try{remoteItems.value=adaptExtensionList(await getAdminPendingSpecialExtensions({page_size:100})).items}catch(error){window.alert(getApiErrorMessage(error,'特殊延期列表加载失败'))}}
onMounted(loadItems)
function days(item){return Math.ceil((new Date(`${item.newExpectedResultTime}T00:00:00`)-new Date(`${item.originalExpectedResultTime}T00:00:00`))/86400000)}
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter((item)=>(!item.reviewLevel||item.reviewLevel==='special')&&(!status.value||item.status===status.value)&&(!search||[item.studentName,item.title,item.mainAdvisor?.name].some((value)=>String(value||'').toLowerCase().includes(search))))})
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">A701 · SPECIAL EXTENSION</p><h1>特殊延期审核</h1><p>审核延期范围超过 30 天的无成果申请。</p></div><RouterLink class="back" to="/admin/dashboard">返回管理首页</RouterLink></header><section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名、申请名称或指导老师" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option :value="APPLICATION_STATUS.PENDING_ADMIN_SPECIAL_EXTENSION">特殊延期待管理员审核</option></select></label></section><section class="panel"><div class="panel-head"><h2>待审核特殊延期</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrap"><table><thead><tr><th>申请编号</th><th>学生姓名</th><th>申请名称</th><th>主指导老师</th><th>原预计时间</th><th>新预计时间</th><th>延期天数</th><th>延期原因</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.id }}</td><td>{{ item.studentName }}</td><td>{{ item.title }}</td><td>{{ item.mainAdvisor?.name||'--' }}</td><td>{{ item.originalExpectedResultTime }}</td><td>{{ item.newExpectedResultTime }}</td><td>{{ days(item) }} 天</td><td class="reason">{{ item.extensionReason }}</td><td>{{ item.extensionSubmitTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink class="detail" :to="`/admin/extensions/${item.id}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="11" class="empty">暂无待审核特殊延期申请</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1500px);margin:auto}header,.panel-head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p,.panel-head span{color:#64748b}.back,.detail{color:#2563eb;font-weight:700;text-decoration:none}.back{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.filters{display:grid;grid-template-columns:1fr 320px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit;background:#fff}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{padding:18px 20px}.panel-head h2{margin:0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.reason{max-width:230px;overflow:hidden;text-overflow:ellipsis}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:680px){.page{padding:24px 14px}header{flex-direction:column}.filters{grid-template-columns:1fr}}</style>
