<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { getTaskById,getTaskTypeText } from '../mock/tasks.js'
import { getApplications } from '../mock/applications.js'
import { getTaskResultByTaskId } from '../mock/taskResults.js'
const route=useRoute();const task=computed(()=>getTaskById(route.params.id));const applications=computed(()=>task.value?getApplications().filter((item)=>item.taskId===task.value.taskId):[]);const result=computed(()=>task.value?getTaskResultByTaskId(task.value.taskId):null)
function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
</script>
<template><main class="page"><div class="content"><template v-if="task"><header><div><p class="eyebrow">TASK DETAIL</p><h1>{{ task.title }}</h1><p>{{ task.taskId }}</p></div><StatusTag :status="task.status" /></header><section class="card"><h2>发布与任务信息</h2><dl class="grid"><div><dt>发布来源</dt><dd>{{ task.source==='admin'?'管理员直接发布':'指导老师申请发布' }}</dd></div><div><dt>发布人</dt><dd>{{ task.publisherName||task.advisorName||'--' }}</dd></div><div><dt>发布时间</dt><dd>{{ task.publishTime||'--' }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="task.status" /></dd></div><div><dt>任务类型</dt><dd>{{ getTaskTypeText(task.taskType) }}</dd></div><div><dt>项目类别</dt><dd>{{ task.category||'--' }}</dd></div><div><dt>指导老师</dt><dd>{{ task.advisorName||'--' }}</dd></div><div><dt>任务课时</dt><dd>{{ task.hours }} 课时</dd></div><div><dt>报名开始</dt><dd>{{ task.registrationStartTime||'--' }}</dd></div><div><dt>报名截止</dt><dd>{{ task.registrationDeadline||'--' }}</dd></div><div><dt>成果截止</dt><dd>{{ task.resultDeadline||'--' }}</dd></div><div><dt>人数限制</dt><dd>{{ task.maxParticipants||'不限' }}</dd></div></dl><h3>任务说明</h3><p>{{ task.description }}</p><h3>任务要求</h3><p>{{ task.requirement }}</p><h3>成果要求</h3><p>{{ task.resultRequirement }}</p></section><section class="card"><h2>报名、筛选与团队</h2><dl class="grid"><div><dt>报名人数</dt><dd>{{ task.applicants?.length||0 }}</dd></div><div><dt>已选中人数</dt><dd>{{ task.selectedStudents?.length||0 }}</dd></div><div><dt>队长</dt><dd>{{ task.leaderName||'--' }} {{ task.leaderId||'' }}</dd></div><div><dt>成果提交状态</dt><dd><StatusTag :status="result?.status||'pending'" :text="result?'已提交成果':'未提交成果'" /></dd></div></dl><div class="members"><span v-for="member in task.selectedStudents" :key="member.studentId">{{ member.studentName }}（{{ member.isLeader?'队长':'成员' }}）</span><p v-if="!task.selectedStudents?.length">暂无团队成员</p></div></section><section class="card"><h2>课时申请关联情况</h2><div v-for="item in applications" :key="item.id" class="application"><strong>{{ item.title }} · {{ item.id }}</strong><StatusTag :status="item.status" /></div><p v-if="!applications.length">暂无关联课时申请</p></section><section class="card"><h2>附件材料</h2><div class="files"><article v-for="file in task.attachments" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size }} · {{ file.uploadedAt }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!task.attachments?.length">暂无附件材料</p></div></section><div class="actions"><RouterLink to="/admin/tasks/list">返回任务列表</RouterLink></div></template><section v-else class="card">任务不存在。<RouterLink to="/admin/tasks/list">返回任务列表</RouterLink></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,960px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.members{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.members span{padding:8px 11px;border-radius:8px;background:#f1f5f9}.application,.files article{display:flex;justify-content:space-between;gap:12px;padding:13px;border-bottom:1px solid #e2e8f0}.files small{display:block;color:#64748b}.files button{margin-left:6px}.actions{text-align:right}.actions a,.card>a{display:inline-block;padding:10px 16px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;text-decoration:none;font-weight:700}@media(max-width:650px){.grid{grid-template-columns:1fr}.files article{flex-direction:column}}</style>
