<script setup>
import { computed,onMounted,ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { batchAssignAppealReviewer, getReopenedAppealsForAssignment } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
import { loadReviewerOptions } from '../services/commonDependencyService.js'
const APPEAL_STATUS={PENDING_REVIEW_ASSIGNMENT:'processing'};const keyword=ref('');const status=ref('');const remoteItems=ref([])
const selectedIds=ref([]);const selectedReviewerId=ref('');const reviewerOptions=ref([]);const batchProcessing=ref(false);const batchResult=ref(null)
async function loadItems(){try{remoteItems.value=adaptAppealList(await getReopenedAppealsForAssignment({page_size:100}))}catch(error){window.alert(error?.message||'待分配申诉加载失败')}}
onMounted(async()=>{const [,reviewers]=await Promise.allSettled([loadItems(),loadReviewerOptions()]);if(reviewers.status==='fulfilled')reviewerOptions.value=reviewers.value})
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter((item)=>(!status.value||item.status===status.value)&&(!search||[item.studentName,item.applicationTitle].some((value)=>String(value||'').toLowerCase().includes(search))))})
const allSelected=computed(()=>items.value.length>0&&items.value.every((item)=>selectedIds.value.includes(item.appealId)))
const partiallySelected=computed(()=>!allSelected.value&&items.value.some((item)=>selectedIds.value.includes(item.appealId)))
function toggleAll(event){const ids=items.value.map((item)=>item.appealId);selectedIds.value=event.target.checked?[...new Set([...selectedIds.value,...ids])]:selectedIds.value.filter((id)=>!ids.includes(id))}
async function batchAssign(){
  if(!selectedIds.value.length)return window.alert('请先选择要分配的申诉。')
  if(!selectedReviewerId.value)return window.alert('请选择复审老师。')
  if(batchProcessing.value)return
  if(!window.confirm(`确定将已选择的 ${selectedIds.value.length} 条申诉批量分配给该复审老师吗？`))return
  batchProcessing.value=true
  try{
    const response=await batchAssignAppealReviewer({appeal_ids:selectedIds.value.map(Number),reviewer_teacher_id:Number(selectedReviewerId.value),comment:null})
    const resultItems=Array.isArray(response?.items)?response.items:[]
    const failedItems=resultItems.filter((item)=>item.success===false).map((item)=>({appealId:item.appeal_id??item.id,errorMessage:item.error_message||'分配失败'}))
    batchResult.value={requestedCount:Number(response?.requested_count??selectedIds.value.length),successCount:Number(response?.success_count??resultItems.filter((item)=>item.success===true).length),failedCount:Number(response?.failed_count??failedItems.length),failedItems}
    selectedIds.value=[]
    await loadItems()
  }catch(error){window.alert(error?.message||'批量分配复审老师失败')}
  finally{batchProcessing.value=false}
}
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">A603 · REVIEW ASSIGNMENT</p><h1>申诉后待分配</h1><p>为管理员已受理的申诉分配复审老师。</p></div><RouterLink class="back" to="/admin/appeals-complaints">返回申诉处理</RouterLink></header><section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或申请名称" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option :value="APPEAL_STATUS.PENDING_REVIEW_ASSIGNMENT">管理员已受理，待分配复审老师</option></select></label><label><span>复审老师</span><select v-model="selectedReviewerId"><option value="">请选择复审老师</option><option v-for="reviewer in reviewerOptions" :key="reviewer.reviewerId" :value="reviewer.reviewerId">{{ reviewer.reviewerName }}（{{ reviewer.reviewerId }}）</option></select></label></section><section v-if="batchResult" class="result"><strong>批量分配结果</strong><p>请求 {{ batchResult.requestedCount }} 条，成功 {{ batchResult.successCount }} 条，失败 {{ batchResult.failedCount }} 条。</p><ul v-if="batchResult.failedItems.length"><li v-for="failed in batchResult.failedItems" :key="failed.appealId">申诉 {{ failed.appealId }}：{{ failed.errorMessage }}</li></ul></section><section class="panel"><div class="head"><div><h2>待分配复审申诉</h2><span>共 {{ items.length }} 项，已选择 {{ selectedIds.length }} 项</span></div><button :disabled="!selectedIds.length||!selectedReviewerId||batchProcessing" @click="batchAssign">{{ batchProcessing?'分配中...':'批量分配' }}</button></div><div class="table"><table><thead><tr><th><input type="checkbox" aria-label="全选待分配申诉" :checked="allSelected" :indeterminate.prop="partiallySelected" :disabled="!items.length||batchProcessing" @change="toggleAll" /></th><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>管理员受理时间</th><th>管理员意见</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td><input v-model="selectedIds" type="checkbox" :value="item.appealId" :disabled="batchProcessing" /></td><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.adminHandleTime }}</td><td>{{ item.adminComment||'--' }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/appeals-complaints/assign/${item.appealId}`">分配复审老师</RouterLink></td></tr><tr v-if="!items.length"><td colspan="10" class="empty">暂无待分配复审申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1350px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:1fr 300px 300px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px}.result{margin-bottom:18px;padding:16px;border:1px solid #86efac;border-radius:12px;color:#166534;background:#f0fdf4}.result p{margin:6px 0}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{align-items:center;padding:18px 20px}.head h2{margin:0}.head span{color:#64748b}.head button{padding:9px 14px;border:0;border-radius:9px;color:#fff;background:#2563eb;font-weight:700;cursor:pointer}.head button:disabled{opacity:.5;cursor:not-allowed}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}input[type=checkbox]{width:17px;height:17px;accent-color:#2563eb}.empty{text-align:center;color:#64748b}@media(max-width:850px){.filters{grid-template-columns:1fr}}@media(max-width:650px){.head{align-items:stretch;flex-direction:column}}</style>
