<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { getTaskTypeText } from '../mock/tasks.js'
import { approveTaskPublish, getTaskPublishRequest, rejectTaskPublish } from '../api/taskApi.js'
import { adaptTaskEnvelope } from '../adapters/taskAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const route=useRoute();const router=useRouter();const comment=ref('');const feedback=ref('')
const task=ref(null);onMounted(loadTask);async function loadTask(){try{task.value=adaptTaskEnvelope(await getTaskPublishRequest(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'任务详情加载失败'))}}
const canProcess=computed(()=>task.value?.status==='pending_publish_review')
function back(){router.push('/admin/tasks/publish-confirm')}
async function approve(){if(!canProcess.value)return;if(!window.confirm('确定正式发布该任务吗？'))return;try{const result=await approveTaskPublish(task.value.id,{comment:comment.value.trim()});task.value={...task.value,status:result?.status??'published'};window.alert('任务已确认发布，学生端任务广场可见。');back()}catch(error){window.alert(getApiErrorMessage(error,'确认发布失败'))}}
async function reject(){if(!canProcess.value)return;if(!comment.value.trim()){feedback.value='驳回发布必须填写处理意见。';return window.alert(feedback.value)};try{await rejectTaskPublish(task.value.id,{comment:comment.value.trim()});window.alert('任务已驳回，已退回指导老师端。');back()}catch(error){window.alert(getApiErrorMessage(error,'驳回发布失败'))}}
function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}
function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
</script>
<template><main class="page"><div class="content"><template v-if="task"><header class="header"><div><p class="eyebrow">A102 · PUBLISH CONFIRMATION DETAIL</p><h1>{{ task.title }}</h1><p>{{ task.taskId }}</p></div><StatusTag :status="task.status" /></header>
<section class="card"><h2>任务基本信息</h2><dl class="grid"><div><dt>任务名称</dt><dd>{{ task.title }}</dd></div><div><dt>任务类型</dt><dd>{{ getTaskTypeText(task.taskType) }}</dd></div><div><dt>报名截止时间</dt><dd>{{ task.registrationDeadline }}</dd></div><div><dt>提交时间</dt><dd>{{ task.submitTime||'--' }}</dd></div><div class="wide"><dt>任务说明</dt><dd>{{ task.description||'--' }}</dd></div><div class="wide"><dt>报名条件</dt><dd>{{ task.requirement||'不限' }}</dd></div><div class="wide"><dt>成果提交要求</dt><dd>{{ task.resultRequirement||'--' }}</dd></div></dl></section>
<section class="card"><h2>发布人信息</h2><dl class="grid"><div><dt>指导老师</dt><dd>{{ task.advisorName }}</dd></div><div><dt>指导老师编号</dt><dd>{{ task.advisorId }}</dd></div><div><dt>任务来源</dt><dd>指导老师发布</dd></div><div><dt>当前确认状态</dt><dd><StatusTag :status="task.status" /></dd></div></dl></section>
<section class="card"><h2>附件材料</h2><div class="files"><article v-for="file in task.attachments" :key="file.id||file.name"><div><strong>{{ file.name }}</strong><small>文件类型：{{ file.type||'未知类型' }} · 文件大小：{{ file.size||'--' }} · 上传时间：{{ file.uploadedAt||'--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!task.attachments?.length" class="empty">暂无附件材料。</p></div></section>
<section class="card"><h2>管理员处理</h2><template v-if="canProcess"><label for="comment">管理员处理意见</label><textarea id="comment" v-model="comment" rows="5" placeholder="请输入处理意见；驳回发布时必填。"></textarea><p v-if="feedback" class="feedback">{{ feedback }}</p></template><dl v-else class="grid"><div><dt>管理员处理意见</dt><dd>{{ task.adminComment||'无' }}</dd></div><div><dt>管理员确认时间</dt><dd>{{ task.adminConfirmTime||'--' }}</dd></div><div><dt>正式发布时间</dt><dd>{{ task.publishTime||'--' }}</dd></div></dl></section>
<div class="actions"><button class="back" @click="back">返回</button><button class="reject" :disabled="!canProcess" @click="reject">驳回发布</button><button class="approve" :disabled="!canProcess" @click="approve">确认发布</button></div>
</template><section v-else class="card empty"><h1>未找到任务发布申请</h1><button class="back" @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,980px);margin:auto}.header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}.header h1{margin:0}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px;font-size:19px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}.wide{grid-column:1/-1}.grid dt{color:#64748b;font-size:13px}.grid dd{margin:5px 0 0;font-weight:600;line-height:1.7}.files{display:grid;gap:10px}.files article{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:14px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.files small{display:block;margin-top:5px;color:#64748b}.files article>div:last-child{display:flex;gap:8px}.files button{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#1d4ed8;background:#fff;font-weight:700;cursor:pointer}label{font-weight:700}textarea{width:100%;margin-top:10px;padding:11px;border:1px solid #cbd5e1;border-radius:9px;resize:vertical;font:inherit}.feedback{color:#b91c1c}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button,.empty button{padding:10px 18px;border-radius:9px;font:inherit;font-weight:700;cursor:pointer}.back{border:1px solid #cbd5e1;background:#fff}.reject{border:0;color:#fff;background:#dc2626}.approve{border:0;color:#fff;background:#2563eb}button:disabled{opacity:.5;cursor:not-allowed}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}.header,.files article{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.actions{flex-wrap:wrap}}</style>
