<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getTasks, getTaskTypeText } from '../mock/tasks.js'
const keyword=ref('');const status=ref('');const source=ref('')
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return getTasks().filter((item)=>(!status.value||item.status===status.value)&&(!source.value||item.source===source.value)&&(!search||item.title.toLowerCase().includes(search))).sort((a,b)=>String(b.publishTime||b.submitTime).localeCompare(String(a.publishTime||a.submitTime)))})
const statuses=computed(()=>[...new Set(getTasks().map((item)=>item.status))])
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">TASK LIST</p><h1>任务列表</h1><p>只用于查看系统全部任务及状态，不承担发布和确认操作。</p></div><RouterLink class="back" to="/admin/tasks">返回任务管理</RouterLink></header><section class="filters"><label><span>任务状态</span><select v-model="status"><option value="">全部状态</option><option v-for="item in statuses" :key="item">{{ item }}</option></select></label><label><span>发布来源</span><select v-model="source"><option value="">全部来源</option><option value="admin">管理员直接发布</option><option value="advisor">指导老师申请发布</option></select></label><label><span>搜索</span><input v-model="keyword" placeholder="搜索任务名称" /></label></section><section class="panel"><div class="head"><h2>全部任务</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>任务编号</th><th>任务名称</th><th>任务类型</th><th>发布来源</th><th>指导老师</th><th>任务状态</th><th>报名人数</th><th>已选中人数</th><th>队长</th><th>报名截止时间</th><th>成果提交时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.taskId"><td>{{ item.taskId }}</td><td>{{ item.title }}</td><td>{{ getTaskTypeText(item.taskType) }}</td><td>{{ item.source==='admin'?'管理员直接发布':'指导老师申请发布' }}</td><td>{{ item.advisorName||'--' }}</td><td><StatusTag :status="item.status" /></td><td>{{ item.applicants?.length||0 }}</td><td>{{ item.selectedStudents?.length||0 }}</td><td>{{ item.leaderName||'--' }}</td><td>{{ item.registrationDeadline||'--' }}</td><td>{{ item.resultDeadline||'--' }}</td><td><RouterLink :to="`/admin/tasks/list/${item.taskId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td class="empty" colspan="12">暂无任务</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1450px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:220px 230px 1fr;gap:14px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:700px){.filters{grid-template-columns:1fr}}</style>
