<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getAdminAppeals } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
const keyword = ref(''); const result = ref('')
const remoteItems=ref([]);onMounted(async()=>{try{remoteItems.value=adaptAppealList(await getAdminAppeals({page_size:100}))}catch(error){window.alert(error?.message||'待最终确认申诉加载失败')}})
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return remoteItems.value.filter(item=>item.reopenStage==='pending_admin_final').filter((item) => (!result.value || item.reviewResult === result.value) && (!search || [item.studentName, item.applicationTitle, item.reviewTeacherName].some((value) => String(value || '').toLowerCase().includes(search)))) })
</script>
<template><main class="page"><div class="content"><header><div><p class="breadcrumb">管理端 / 最终确认 / 申诉复审最终确认</p><p class="eyebrow">A605 · APPEAL FINAL CONFIRM</p><h1>申诉复审最终确认</h1><p>确认审核老师的申诉复审结论，并在复审通过时更新原课时结果。</p></div><RouterLink class="back" to="/admin/dashboard">返回管理首页</RouterLink></header>
<nav class="type-tabs"><RouterLink to="/admin/final-confirm">课时最终确认</RouterLink><RouterLink to="/admin/final-confirm/exchanges">学分兑换最终确认</RouterLink><RouterLink class="active" to="/admin/final-confirm/appeals">申诉复审最终确认</RouterLink></nav>
<section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名、申请名称或复审老师" /></label><label><span>复审结果</span><select v-model="result"><option value="">全部</option><option value="approved">复审通过</option><option value="rejected">复审驳回</option></select></label></section>
<section class="panel"><div class="head"><h2>待最终确认申诉</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>复审结果</th><th>复审课时</th><th>复审老师</th><th>复审时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.reviewResult === 'approved' ? '复审通过' : '复审驳回' }}</td><td>{{ item.reviewHours ?? '--' }}</td><td>{{ item.reviewTeacherName || '--' }}</td><td>{{ item.reviewTime || '--' }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/final-confirm/appeals/${item.appealId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="11" class="empty">暂无待最终确认申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1380px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:18px}h1{margin:0}.breadcrumb{margin:0 0 8px;color:#64748b;font-size:13px}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.type-tabs{display:flex;gap:8px;margin-bottom:18px;padding:6px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.type-tabs a{padding:10px 16px;border-radius:8px;color:#475569;text-decoration:none;font-weight:700}.type-tabs .active{color:#1d4ed8;background:#dbeafe}.filters{display:grid;grid-template-columns:1fr 280px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}.type-tabs{flex-wrap:wrap}}</style>
