<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getComplaints } from '../mock/complaints.js'
const type = ref(''); const status = ref(''); const keyword = ref('')
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return getComplaints().filter((item) => (!type.value || item.complaintType === type.value) && (!status.value || item.status === status.value) && (!search || item.relatedApplicationTitle.toLowerCase().includes(search))).sort((a, b) => b.submitTime.localeCompare(a.submitTime)) })
const types = ['流程问题', '材料问题', '处理结果问题', '人员沟通问题', '其他问题']
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">A801 · COMPLAINT MANAGEMENT</p><h1>投诉管理</h1><p>查看学生匿名投诉并记录处理结果。</p></div><RouterLink class="back" to="/admin/appeals-complaints">返回申诉与投诉</RouterLink></header><nav class="module-nav"><RouterLink to="/admin/appeals-complaints">申诉处理</RouterLink><RouterLink to="/admin/appeals-complaints/assign">申诉复审分配</RouterLink><RouterLink class="active" to="/admin/appeals-complaints/complaints">投诉管理</RouterLink></nav>
<section class="filters"><label><span>投诉类型</span><select v-model="type"><option value="">全部类型</option><option v-for="item in types" :key="item">{{ item }}</option></select></label><label><span>状态</span><select v-model="status"><option value="">全部状态</option><option value="pending_admin">待管理员处理</option><option value="processed">已处理</option></select></label><label><span>关联申请名称</span><input v-model="keyword" placeholder="搜索关联申请名称" /></label></section>
<section class="panel"><div class="head"><h2>投诉记录</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>投诉编号</th><th>投诉类型</th><th>是否匿名</th><th>是否关联申请</th><th>关联申请名称</th><th>提交时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.complaintId"><td>{{ item.complaintId }}</td><td>{{ item.complaintType }}</td><td>{{ item.isAnonymous ? '匿名' : '实名' }}</td><td>{{ item.relatedApplicationId ? '是' : '否' }}</td><td>{{ item.relatedApplicationTitle || '--' }}</td><td>{{ item.submitTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/appeals-complaints/complaints/${item.complaintId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="8" class="empty">暂无投诉记录</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1250px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:18px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a,.module-nav a{color:#2563eb;font-weight:700;text-decoration:none}.module-nav{display:flex;gap:10px;margin-bottom:18px}.module-nav a{padding:10px 14px;border:1px solid #bfdbfe;border-radius:9px;background:#fff}.module-nav .active{color:#fff;background:#2563eb}.filters{display:grid;grid-template-columns:220px 220px 1fr;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:700px){.filters{grid-template-columns:1fr}.module-nav{flex-wrap:wrap}}</style>
