<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { APPEAL_STATUS, getAdminPendingAppeals, getPendingReviewAssignmentAppeals } from '../mock/appeals.js'
const keyword = ref(''); const status = ref(APPEAL_STATUS.PENDING_ADMIN)
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return getAdminPendingAppeals().filter((item) => (!status.value || item.status === status.value) && (!search || [item.studentName, item.applicationTitle].some((value) => String(value || '').toLowerCase().includes(search)))) })
const assignCount = computed(() => getPendingReviewAssignmentAppeals().length)
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">A601 · APPEAL MANAGEMENT</p><h1>申诉与投诉</h1><p>处理申诉受理、复审老师分配及投诉等前置事项。</p></div><RouterLink class="back" to="/admin/dashboard">返回管理首页</RouterLink></header>
<nav class="module-nav"><RouterLink to="/admin/appeals-complaints">申诉处理（{{ items.length }}）</RouterLink><RouterLink to="/admin/appeals-complaints/assign">申诉复审分配（{{ assignCount }}）</RouterLink><RouterLink to="/admin/appeals-complaints/complaints">投诉管理</RouterLink></nav>
<section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或申请名称" /></label><label><span>申诉状态</span><select v-model="status"><option value="">全部</option><option :value="APPEAL_STATUS.PENDING_ADMIN">待管理员处理</option></select></label></section>
<section class="panel"><div class="head"><h2>待处理申诉</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>提交时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.submitTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/appeals-complaints/${item.appealId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="8" class="empty">暂无待处理申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1250px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a,.module-nav a{color:#2563eb;font-weight:700;text-decoration:none}.module-nav{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:18px}.module-nav a{padding:10px 14px;border:1px solid #bfdbfe;border-radius:9px;background:#fff}.module-nav a.router-link-exact-active{color:#fff;background:#2563eb}.filters{display:grid;grid-template-columns:1fr 300px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}}</style>
