<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { batchFinalApproveReopenedAppeals, getAdminAppeals } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
const keyword = ref(''); const result = ref('')
const selectedIds=ref([]);const batchProcessing=ref(false);const batchResult=ref(null)
const remoteItems=ref([]);async function loadItems(){try{remoteItems.value=adaptAppealList(await getAdminAppeals({page_size:100}))}catch(error){window.alert(error?.message||'待最终确认申诉加载失败')}}onMounted(loadItems)
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return remoteItems.value.filter(item=>item.reopenStage==='pending_admin_final').filter((item) => (!result.value || item.reviewResult === result.value) && (!search || [item.studentName, item.applicationTitle, item.reviewTeacherName].some((value) => String(value || '').toLowerCase().includes(search)))) })
const allSelected=computed(()=>items.value.length>0&&items.value.every((item)=>selectedIds.value.includes(item.appealId)))
const partiallySelected=computed(()=>!allSelected.value&&items.value.some((item)=>selectedIds.value.includes(item.appealId)))
function toggleAll(event){const ids=items.value.map((item)=>item.appealId);selectedIds.value=event.target.checked?[...new Set([...selectedIds.value,...ids])]:selectedIds.value.filter((id)=>!ids.includes(id))}
async function batchConfirm(){
  if(!selectedIds.value.length)return window.alert('请先选择要最终确认的申诉。')
  if(batchProcessing.value)return
  if(!window.confirm(`确定批量最终确认已选择的 ${selectedIds.value.length} 条申诉吗？`))return
  batchProcessing.value=true
  try{
    const response=await batchFinalApproveReopenedAppeals({appeal_ids:selectedIds.value.map(Number),comment:null})
    const resultItems=Array.isArray(response?.items)?response.items:[]
    const failedItems=resultItems.filter((item)=>item.success===false).map((item)=>({appealId:item.appeal_id??item.id,errorMessage:item.error_message||'最终确认失败'}))
    batchResult.value={requestedCount:Number(response?.requested_count??selectedIds.value.length),successCount:Number(response?.success_count??resultItems.filter((item)=>item.success===true).length),failedCount:Number(response?.failed_count??failedItems.length),failedItems}
    selectedIds.value=[]
    await loadItems()
  }catch(error){window.alert(error?.message||'批量最终确认申诉失败')}
  finally{batchProcessing.value=false}
}
</script>
<template><main class="page"><div class="content"><header><div><p class="breadcrumb">管理端 / 最终确认 / 申诉复审最终确认</p><p class="eyebrow">A605 · APPEAL FINAL CONFIRM</p><h1>申诉复审最终确认</h1><p>确认审核老师的申诉复审结论，并在复审通过时更新原课时结果。</p></div><RouterLink class="back" to="/admin/dashboard">返回管理首页</RouterLink></header>
<nav class="type-tabs"><RouterLink to="/admin/final-confirm">课时最终确认</RouterLink><RouterLink to="/admin/final-confirm/exchanges">学分兑换最终确认</RouterLink><RouterLink class="active" to="/admin/final-confirm/appeals">申诉复审最终确认</RouterLink></nav>
<section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名、申请名称或复审老师" /></label><label><span>复审结果</span><select v-model="result"><option value="">全部</option><option value="approved">复审通过</option><option value="rejected">复审驳回</option></select></label></section>
<section v-if="batchResult" class="result-card"><strong>批量最终确认结果</strong><p>请求 {{ batchResult.requestedCount }} 条，成功 {{ batchResult.successCount }} 条，失败 {{ batchResult.failedCount }} 条。</p><ul v-if="batchResult.failedItems.length"><li v-for="failed in batchResult.failedItems" :key="failed.appealId">申诉 {{ failed.appealId }}：{{ failed.errorMessage }}</li></ul></section>
<section class="panel"><div class="head"><div><h2>待最终确认申诉</h2><span>共 {{ items.length }} 项，已选择 {{ selectedIds.length }} 项</span></div><button :disabled="!selectedIds.length||batchProcessing" @click="batchConfirm">{{ batchProcessing?'确认中...':'批量最终确认' }}</button></div><div class="table"><table><thead><tr><th><input type="checkbox" aria-label="全选待最终确认申诉" :checked="allSelected" :indeterminate.prop="partiallySelected" :disabled="!items.length||batchProcessing" @change="toggleAll" /></th><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>复审结果</th><th>复审课时</th><th>复审老师</th><th>复审时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td><input v-model="selectedIds" type="checkbox" :value="item.appealId" :disabled="batchProcessing" /></td><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.reviewResult === 'approved' ? '复审通过' : '复审驳回' }}</td><td>{{ item.reviewHours ?? '--' }}</td><td>{{ item.reviewTeacherName || '--' }}</td><td>{{ item.reviewTime || '--' }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/final-confirm/appeals/${item.appealId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="12" class="empty">暂无待最终确认申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1380px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:18px}h1{margin:0}.breadcrumb{margin:0 0 8px;color:#64748b;font-size:13px}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.type-tabs{display:flex;gap:8px;margin-bottom:18px;padding:6px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.type-tabs a{padding:10px 16px;border-radius:8px;color:#475569;text-decoration:none;font-weight:700}.type-tabs .active{color:#1d4ed8;background:#dbeafe}.filters{display:grid;grid-template-columns:1fr 280px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.result-card{margin-bottom:18px;padding:16px;border:1px solid #86efac;border-radius:12px;color:#166534;background:#f0fdf4}.result-card p{margin:6px 0}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{align-items:center;padding:18px 20px}.head h2{margin:0}.head span{color:#64748b}.head button{padding:9px 14px;border:0;border-radius:9px;color:#fff;background:#2563eb;font-weight:700;cursor:pointer}.head button:disabled{opacity:.5;cursor:not-allowed}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}input[type=checkbox]{width:17px;height:17px;accent-color:#2563eb}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}.type-tabs{flex-wrap:wrap}.head{align-items:stretch;flex-direction:column}}</style>
