<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { COMPLAINT_STATUS, getComplaintById, processComplaint } from '../mock/complaints.js'
import { getApplications } from '../mock/applications.js'
const route = useRoute(); const router = useRouter(); const comment = ref(''); const complaint = computed(() => getComplaintById(route.params.id)); const application = computed(() => complaint.value?.relatedApplicationId ? getApplications().find((item) => item.id === complaint.value.relatedApplicationId) : null); const pending = computed(() => complaint.value?.status === COMPLAINT_STATUS.PENDING_ADMIN)
function back() { router.push('/admin/appeals-complaints/complaints') } function preview() { window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。') } function download() { window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。') }
function process() { if (!comment.value.trim()) return window.alert('请填写管理员处理意见。'); if (!processComplaint(complaint.value.complaintId, comment.value)) return window.alert('投诉处理失败。'); window.alert('投诉已处理。'); back() }
</script>
<template><main class="page"><div class="content"><template v-if="complaint"><header><div><p class="eyebrow">A802 · COMPLAINT DETAIL</p><h1>投诉详情</h1><p>{{ complaint.complaintId }}</p></div><StatusTag :status="complaint.status" /></header><section class="card"><h2>投诉基本信息</h2><dl class="grid"><div><dt>投诉类型</dt><dd>{{ complaint.complaintType }}</dd></div><div><dt>提交方式</dt><dd>{{ complaint.isAnonymous ? '匿名投诉' : '实名投诉' }}</dd></div><div><dt>提交时间</dt><dd>{{ complaint.submitTime }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="complaint.status" /></dd></div><div><dt>是否关联申请</dt><dd>{{ complaint.relatedApplicationId ? '是' : '否' }}</dd></div><div><dt>关联申请</dt><dd>{{ complaint.relatedApplicationTitle || '--' }}</dd></div></dl></section>
<section v-if="application" class="card"><h2>关联课时申请信息</h2><dl class="grid"><div><dt>申请编号</dt><dd>{{ application.id }}</dd></div><div><dt>申请名称</dt><dd>{{ application.title }}</dd></div><div><dt>申请状态</dt><dd><StatusTag :status="application.status" /></dd></div><div><dt>申请课时</dt><dd>{{ application.requestedHours }} 课时</dd></div></dl><p class="notice">投诉处理不会改变该课时申请状态。</p></section><section class="card"><h2>投诉内容</h2><p>{{ complaint.complaintContent }}</p></section>
<section class="card"><h2>投诉材料</h2><div class="files"><article v-for="file in complaint.complaintMaterials" :key="file.id"><div><strong>{{ file.fileName }}</strong><small>{{ file.fileType }} · {{ file.fileSize }} · {{ file.uploadTime }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!complaint.complaintMaterials.length">暂无附件材料</p></div></section>
<section class="card"><h2>管理员处理</h2><template v-if="pending"><label>处理意见<textarea v-model="comment" rows="5" placeholder="标记已处理时必填"></textarea></label></template><dl v-else class="grid"><div><dt>处理意见</dt><dd>{{ complaint.adminComment }}</dd></div><div><dt>处理时间</dt><dd>{{ complaint.adminHandleTime }}</dd></div></dl></section><div class="actions"><button @click="back">返回</button><button v-if="pending" class="primary" @click="process">标记已处理</button></div></template><section v-else class="card">投诉记录不存在。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,920px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.notice{color:#64748b}.files{display:grid;gap:10px}.files article{display:flex;justify-content:space-between;gap:12px;padding:13px;background:#f8fafc}.files small{display:block;color:#64748b}.files button,.actions button,.card>button{padding:8px 12px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff}.card label{display:grid;gap:8px;font-weight:700}.card textarea{padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.actions{display:flex;justify-content:flex-end;gap:10px}.actions .primary{color:#fff;background:#2563eb}@media(max-width:650px){.grid{grid-template-columns:1fr}.files article{flex-direction:column}}</style>
