<script setup>
import { computed,onMounted,ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getReopenedAppealsForAssignment } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
const APPEAL_STATUS={PENDING_REVIEW_ASSIGNMENT:'processing'};const keyword=ref('');const status=ref('');const remoteItems=ref([])
onMounted(async()=>{try{remoteItems.value=adaptAppealList(await getReopenedAppealsForAssignment({page_size:100}))}catch(error){window.alert(error?.message||'待分配申诉加载失败')}})
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter((item)=>(!status.value||item.status===status.value)&&(!search||[item.studentName,item.applicationTitle].some((value)=>String(value||'').toLowerCase().includes(search))))})
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">A603 · REVIEW ASSIGNMENT</p><h1>申诉后待分配</h1><p>为管理员已受理的申诉分配复审老师。</p></div><RouterLink class="back" to="/admin/appeals-complaints">返回申诉处理</RouterLink></header><section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或申请名称" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option :value="APPEAL_STATUS.PENDING_REVIEW_ASSIGNMENT">管理员已受理，待分配复审老师</option></select></label></section><section class="panel"><div class="head"><h2>待分配复审申诉</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>管理员受理时间</th><th>管理员意见</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.adminHandleTime }}</td><td>{{ item.adminComment||'--' }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/admin/appeals-complaints/assign/${item.appealId}`">分配复审老师</RouterLink></td></tr><tr v-if="!items.length"><td colspan="9" class="empty">暂无待分配复审申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1350px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:1fr 340px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}}</style>
