<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getTasks } from '../mock/tasks.js'
import { getApplications } from '../mock/applications.js'
import { getExchanges } from '../mock/exchanges.js'
import { getAppeals } from '../mock/appeals.js'
import { getComplaints } from '../mock/complaints.js'

const type = ref(''); const result = ref(''); const keyword = ref(''); const selected = ref(null)
const typeOptions = ['任务发布确认', '直接发布任务', '审核分配', '课时最终确认', '学分兑换最终确认', '特殊延期审核', '申诉处理', '申诉复审分配', '申诉最终确认', '投诉处理']
const resultText = (value) => ({ approved: '通过', rejected: '驳回', assigned: '已分配', accepted: '已受理', not_accepted: '不受理', published: '已发布', processed: '已处理', confirmed: '已确认' }[value] || value || '--')
function record(data) { return { person: '--', comment: '--', beforeStatus: '--', afterStatus: '--', currentStatus: '', detail: {}, ...data } }

const allRecords = computed(() => {
  const records = []
  getTasks().forEach((item) => {
    if (item.source === 'advisor' && item.adminConfirmTime) records.push(record({ id: `TASK-${item.taskId}`, type: '任务发布确认', title: item.title, person: item.advisorName, result: item.publishTime ? 'approved' : 'rejected', comment: item.adminComment, time: item.adminConfirmTime, beforeStatus: 'pending_admin_publish', afterStatus: item.publishTime ? 'published' : 'publish_rejected', currentStatus: item.status, detail: { 任务编号: item.taskId, 任务类型: item.taskType, 指导老师: item.advisorName, 报名截止时间: item.registrationDeadline } }))
    if (item.source === 'admin' && (item.publishTime || item.submitTime)) records.push(record({ id: `DIRECT-${item.taskId}`, type: '直接发布任务', title: item.title, person: '系统管理员', result: 'published', comment: item.adminComment || '管理员直接发布任务', time: item.publishTime || item.submitTime, beforeStatus: 'draft', afterStatus: 'published', currentStatus: item.status, detail: { 任务编号: item.taskId, 任务类型: item.taskType, 报名截止时间: item.registrationDeadline } }))
  })
  getApplications().forEach((item) => {
    if (item.adminAcceptTime && item.reviewerId) records.push(record({ id: `ASSIGN-${item.id}`, type: '审核分配', title: item.title, person: `${item.studentName} / ${item.reviewer?.name || item.reviewerId}`, result: 'assigned', comment: item.adminAcceptComment || '已分配审核老师', time: item.adminAcceptTime, beforeStatus: 'pending_admin_accept', afterStatus: 'pending_reviewer', currentStatus: item.status, detail: { 申请编号: item.id, 学生姓名: item.studentName, 审核老师: item.reviewer?.name || item.reviewerId, 申请课时: item.requestedHours } }))
    if (item.finalConfirmTime) records.push(record({ id: `FINAL-${item.id}`, type: '课时最终确认', title: item.title, person: item.studentName, result: item.finalStatus === 'rejected' || item.status === 'final_rejected' ? 'rejected' : 'approved', comment: item.finalComment, time: item.finalConfirmTime, beforeStatus: 'pending_admin_final', afterStatus: item.finalStatus === 'rejected' || item.status === 'final_rejected' ? 'final_rejected' : 'final_approved', currentStatus: item.status, detail: { 申请编号: item.id, 学生姓名: item.studentName, 申请课时: item.requestedHours, 最终课时: item.recognizedHours ?? item.requestedHours } }))
    if (item.extensionAdminConfirmTime) records.push(record({ id: `EXT-${item.id}`, type: '特殊延期审核', title: item.title, person: item.studentName, result: item.extensionStatus, comment: item.extensionAdminComment, time: item.extensionAdminConfirmTime, beforeStatus: 'pending_admin_special_extension', afterStatus: 'pending_material', currentStatus: item.status, detail: { 申请编号: item.id, 原预计时间: item.originalExpectedResultTime, 新预计时间: item.newExpectedResultTime, 延期类型: item.extensionType } }))
  })
  getExchanges().filter((item) => item.finalConfirmTime).forEach((item) => records.push(record({ id: `EXCHANGE-${item.id}`, type: '学分兑换最终确认', title: item.taskName || item.projectTitle, person: item.captainName || item.studentName, result: item.finalStatus === 'rejected' || item.status === 'final_rejected' ? 'rejected' : 'approved', comment: item.finalComment, time: item.finalConfirmTime, beforeStatus: 'pending_final_confirm', afterStatus: item.status, currentStatus: item.status, detail: { 兑换编号: item.exchangeId, 队长姓名: item.captainName || item.studentName, 团队名称: item.teamName, 兑换学分: item.estimatedCredits } })))
  getAppeals().forEach((item) => {
    if (item.adminHandleTime) records.push(record({ id: `APPEAL-HANDLE-${item.appealId}`, type: '申诉处理', title: item.applicationTitle, person: item.studentName, result: item.finalResult === 'appeal_rejected' || item.status === 'admin_rejected' ? 'not_accepted' : 'accepted', comment: item.adminComment, time: item.adminHandleTime, beforeStatus: 'pending_admin', afterStatus: item.finalResult === 'appeal_rejected' || item.status === 'admin_rejected' ? 'admin_rejected' : 'pending_review_assignment', currentStatus: item.status, detail: { 申诉编号: item.appealId, 关联申请: item.applicationId, 学生姓名: item.studentName, 原认定课时: item.originalFinalHours } }))
    if (item.reviewAssignTime) records.push(record({ id: `APPEAL-ASSIGN-${item.appealId}`, type: '申诉复审分配', title: item.applicationTitle, person: item.reviewTeacherName, result: 'assigned', comment: `已分配复审老师：${item.reviewTeacherName}`, time: item.reviewAssignTime, beforeStatus: 'pending_review_assignment', afterStatus: 'pending_re_review', currentStatus: item.status, detail: { 申诉编号: item.appealId, 学生姓名: item.studentName, 复审老师: item.reviewTeacherName, 分配管理员: item.assignAdminName } }))
    if (item.finalConfirmTime) records.push(record({ id: `APPEAL-FINAL-${item.appealId}`, type: '申诉最终确认', title: item.applicationTitle, person: item.studentName, result: item.finalResult, comment: item.finalAdminComment, time: item.finalConfirmTime, beforeStatus: item.reviewResult === 'approved' ? 're_review_approved' : 're_review_rejected', afterStatus: 'final_confirmed', currentStatus: item.status, detail: { 申诉编号: item.appealId, 复审老师: item.reviewTeacherName, 复审结果: item.reviewResult, 复审课时: item.reviewHours } }))
  })
  getComplaints().filter((item) => item.adminHandleTime).forEach((item) => records.push(record({ id: `COMPLAINT-${item.complaintId}`, type: '投诉处理', title: item.relatedApplicationTitle || item.complaintType, person: item.isAnonymous ? '匿名投诉人' : item.studentName, result: 'processed', comment: item.adminComment, time: item.adminHandleTime, beforeStatus: 'pending_admin', afterStatus: 'processed', currentStatus: item.status, detail: { 投诉编号: item.complaintId, 投诉类型: item.complaintType, 是否匿名: item.isAnonymous ? '是' : '否', 关联申请: item.relatedApplicationTitle || '--' } })))
  return records.sort((a, b) => String(b.time || '').localeCompare(String(a.time || '')))
})
const resultOptions = computed(() => [...new Set(allRecords.value.map((item) => resultText(item.result)))])
const records = computed(() => { const search = keyword.value.trim().toLowerCase(); return allRecords.value.filter((item) => (!type.value || item.type === type.value) && (!result.value || resultText(item.result) === result.value) && (!search || [item.title, item.person, item.id, ...Object.values(item.detail)].some((value) => String(value || '').toLowerCase().includes(search)))) })
</script>

<template><main class="page"><div class="content"><header><div><p class="eyebrow">A901 · PROCESSED RECORDS</p><h1>已处理记录</h1><p>查看管理员已经完成的业务处理记录，不包含数据统计。</p></div><RouterLink class="back" to="/admin/dashboard">返回管理首页</RouterLink></header>
<section class="filters"><label><span>处理类型</span><select v-model="type"><option value="">全部类型</option><option v-for="item in typeOptions" :key="item">{{ item }}</option></select></label><label><span>处理结果</span><select v-model="result"><option value="">全部结果</option><option v-for="item in resultOptions" :key="item">{{ item }}</option></select></label><label><span>搜索</span><input v-model="keyword" placeholder="学生、任务、申请、申诉或投诉编号" /></label></section>
<section class="panel"><div class="panel-head"><h2>处理记录</h2><span>共 {{ records.length }} 条</span></div><div class="table-wrap"><table><thead><tr><th>记录编号</th><th>处理类型</th><th>关联对象名称</th><th>关联人员</th><th>处理结果</th><th>处理意见</th><th>处理时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in records" :key="item.id"><td>{{ item.id }}</td><td>{{ item.type }}</td><td>{{ item.title }}</td><td>{{ item.person }}</td><td>{{ resultText(item.result) }}</td><td class="comment">{{ item.comment || '--' }}</td><td>{{ item.time }}</td><td><StatusTag :status="item.currentStatus" /></td><td><button class="detail" @click="selected = item">查看详情</button></td></tr><tr v-if="!records.length"><td colspan="9" class="empty">暂无已处理记录</td></tr></tbody></table></div></section>
<div v-if="selected" class="modal-mask" @click.self="selected = null"><section class="modal"><header><div><p class="eyebrow">A902 · RECORD DETAIL</p><h2>已处理记录详情</h2></div><button @click="selected = null">关闭</button></header><dl class="detail-grid"><div><dt>记录编号</dt><dd>{{ selected.id }}</dd></div><div><dt>处理类型</dt><dd>{{ selected.type }}</dd></div><div><dt>关联对象</dt><dd>{{ selected.title }}</dd></div><div><dt>关联人员</dt><dd>{{ selected.person }}</dd></div><div><dt>处理前状态</dt><dd><StatusTag :status="selected.beforeStatus" /></dd></div><div><dt>处理后状态</dt><dd><StatusTag :status="selected.afterStatus" /></dd></div><div><dt>处理结果</dt><dd>{{ resultText(selected.result) }}</dd></div><div><dt>处理时间</dt><dd>{{ selected.time }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="selected.currentStatus" /></dd></div><div class="wide"><dt>处理意见</dt><dd>{{ selected.comment || '--' }}</dd></div><div v-for="(value, label) in selected.detail" :key="label"><dt>{{ label }}</dt><dd>{{ value ?? '--' }}</dd></div></dl><div class="modal-actions"><button @click="selected = null">返回</button></div></section></div>
</div></main></template>

<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1380px);margin:auto}header,.panel-head,.modal header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}header{margin-bottom:22px}h1{margin:0 0 8px}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back{padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;background:#fff;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:240px 220px 1fr;gap:14px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.comment{max-width:240px;overflow:hidden;text-overflow:ellipsis}.detail{border:0;color:#2563eb;background:none;font-weight:700;cursor:pointer}.empty{text-align:center;color:#64748b}.modal-mask{position:fixed;inset:0;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.5);z-index:30}.modal{width:min(100%,780px);max-height:90vh;overflow:auto;padding:24px;border-radius:16px;background:#fff}.modal h2{margin:0}.modal button{padding:8px 13px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.detail-grid .wide{grid-column:1/-1}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.modal-actions{margin-top:24px;text-align:right}@media(max-width:720px){.page{padding:24px 14px}.filters,.detail-grid{grid-template-columns:1fr}.detail-grid .wide{grid-column:auto}header{flex-direction:column}}</style>
