<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { finalConfirmAppeal, getAppealById } from '../mock/appeals.js'
import { getApplications } from '../mock/applications.js'
const route = useRoute(); const router = useRouter(); const comment = ref('')
const appeal = computed(() => { const item = getAppealById(route.params.id); return ['re_review_approved', 're_review_rejected'].includes(item?.status) ? item : null })
const application = computed(() => appeal.value ? getApplications().find((item) => item.id === appeal.value.applicationId) : null)
function back() { router.push('/admin/final-confirm/appeals') }
function preview() { window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。') }
function download() { window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。') }
function confirm() { const approved = appeal.value?.reviewResult === 'approved'; if (!finalConfirmAppeal(appeal.value.appealId, comment.value)) return window.alert('最终确认失败，请检查申诉状态和复审课时。'); window.alert(approved ? '申诉最终确认完成，课时结果已更新。' : '申诉最终确认完成，原课时结果保持不变。'); back() }
</script>
<template><main class="page"><div class="content"><template v-if="appeal"><header><div><p class="breadcrumb">管理端 / 最终确认 / 申诉复审最终确认 / 详情</p><p class="eyebrow">A606 · APPEAL FINAL CONFIRM DETAIL</p><h1>申诉复审最终确认详情</h1><p>{{ appeal.appealId }}</p></div><StatusTag :status="appeal.status" /></header>
<section class="card"><h2>申诉与学生信息</h2><dl class="grid"><div><dt>关联申请</dt><dd>{{ appeal.applicationTitle }}</dd></div><div><dt>学生</dt><dd>{{ appeal.studentName }}（{{ appeal.studentId }}）</dd></div><div><dt>课时申请编号</dt><dd>{{ appeal.applicationId }}</dd></div><div><dt>原申请状态</dt><dd><StatusTag :status="appeal.originalStatus" /></dd></div><div><dt>原认定 / 最终课时</dt><dd>{{ appeal.originalFinalHours }} 课时</dd></div><div><dt>申诉提交时间</dt><dd>{{ appeal.submitTime }}</dd></div></dl></section>
<section class="card"><h2>原课时申请处理信息</h2><dl class="grid"><div><dt>原审核意见</dt><dd>{{ application?.reviewComment || '--' }}</dd></div><div><dt>原管理员最终确认意见</dt><dd>{{ application?.finalComment || '--' }}</dd></div><div><dt>原申请课时</dt><dd>{{ application?.requestedHours ?? '--' }} 课时</dd></div><div><dt>当前认定课时</dt><dd>{{ application?.recognizedHours ?? appeal.originalFinalHours }} 课时</dd></div></dl></section>
<section class="card"><h2>申诉内容</h2><p><strong>申诉原因：</strong>{{ appeal.appealReason }}</p><p><strong>管理员受理意见：</strong>{{ appeal.adminComment || '--' }}</p><div class="files"><article v-for="file in appeal.appealMaterials" :key="file.id"><div><strong>{{ file.name || file.fileName }}</strong><small>{{ file.type || file.fileType }} · {{ file.size || file.fileSize || '--' }} · {{ file.uploadedAt || file.uploadTime || '--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!appeal.appealMaterials.length">暂无附件材料</p></div></section>
<section class="card"><h2>复审结果</h2><dl class="grid"><div><dt>复审老师</dt><dd>{{ appeal.reviewTeacherName }}（{{ appeal.reviewTeacherId }}）</dd></div><div><dt>复审时间</dt><dd>{{ appeal.reviewTime || '--' }}</dd></div><div><dt>复审结果</dt><dd>{{ appeal.reviewResult === 'approved' ? '复审通过' : '复审驳回' }}</dd></div><div><dt>复审课时</dt><dd>{{ appeal.reviewHours ?? '--' }} 课时</dd></div><div class="wide"><dt>复审意见</dt><dd>{{ appeal.reviewComment || '--' }}</dd></div></dl></section>
<section class="card"><h2>管理员最终确认</h2><label>最终确认意见<textarea v-model="comment" rows="5" placeholder="请输入最终确认意见（可选）"></textarea></label><p class="notice">{{ appeal.reviewResult === 'approved' ? '确认后将按复审课时更新原课时申请结果。' : '确认后申诉流程结束，原课时申请结果保持不变。' }}</p></section>
<div class="actions"><button @click="back">返回</button><button class="primary" @click="confirm">最终确认</button></div></template><section v-else class="card empty">申诉不存在或当前不处于待最终确认状态。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,960px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.wide{grid-column:1/-1}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.files{display:grid;gap:10px;margin-top:16px}.files article{display:flex;justify-content:space-between;gap:12px;padding:13px;background:#f8fafc}.files small{display:block;color:#64748b}.files button,.actions button,.empty button{padding:8px 12px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff}.card label{display:grid;gap:8px;font-weight:700}.card textarea{padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.notice{color:#475569}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button{padding:10px 18px}.actions .primary{color:#fff;background:#2563eb}.empty{text-align:center}.empty button{display:block;margin:16px auto 0}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.files article{flex-direction:column}}</style>
