<script setup>
import { computed,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { APPEAL_STATUS,assignReviewTeacher,getAppealById,getReviewerPendingAppeals } from '../mock/appeals.js'
import { getApplications,mockReviewers } from '../mock/applications.js'
const route=useRoute();const router=useRouter();const selectedId=ref('');const appeal=computed(()=>getAppealById(route.params.id));const application=computed(()=>appeal.value?getApplications().find((item)=>item.id===appeal.value.applicationId):null);const pending=computed(()=>appeal.value?.status===APPEAL_STATUS.PENDING_REVIEW_ASSIGNMENT)
const reviewers=computed(()=>mockReviewers.map((item)=>({...item,appealPendingCount:getReviewerPendingAppeals(item.reviewerId).length})))
function back(){router.push('/admin/appeals-complaints/assign')}function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
function assign(){if(!pending.value)return window.alert('该申诉已完成复审老师分配。');if(!selectedId.value)return window.alert('请选择一名复审老师。');const teacher=reviewers.value.find((item)=>item.reviewerId===selectedId.value);if(!assignReviewTeacher(appeal.value.appealId,teacher))return window.alert('复审老师分配失败。');window.alert('复审老师分配成功，等待审核老师复审。');back()}
</script>
<template><main class="page"><div class="content"><template v-if="appeal"><header><div><p class="eyebrow">A604 · ASSIGN REVIEWER</p><h1>分配复审老师</h1><p>{{ appeal.appealId }}</p></div><StatusTag :status="appeal.status" /></header><section class="card"><h2>申诉与原申请</h2><dl class="grid"><div><dt>关联申请</dt><dd>{{ appeal.applicationTitle }}</dd></div><div><dt>学生</dt><dd>{{ appeal.studentName }}（{{ appeal.studentId }}）</dd></div><div><dt>原申请状态</dt><dd><StatusTag :status="appeal.originalStatus" /></dd></div><div><dt>原认定/最终课时</dt><dd>{{ appeal.originalFinalHours }} 课时</dd></div><div><dt>申请课时</dt><dd>{{ application?.requestedHours??'--' }} 课时</dd></div><div><dt>管理员受理意见</dt><dd>{{ appeal.adminComment||'--' }}</dd></div><div class="wide"><dt>原审核意见或驳回原因</dt><dd>{{ appeal.originalComment||'--' }}</dd></div><div class="wide"><dt>学生申诉原因</dt><dd>{{ appeal.appealReason }}</dd></div></dl></section><section class="card"><h2>申诉材料</h2><div class="files"><article v-for="file in appeal.appealMaterials" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!appeal.appealMaterials.length">暂无附件材料</p></div></section><section class="card"><h2>选择复审老师</h2><div class="reviewers"><label v-for="teacher in reviewers" :key="teacher.reviewerId"><input v-model="selectedId" type="radio" :value="teacher.reviewerId" :disabled="!pending" /><span><strong>{{ teacher.reviewerName }}（{{ teacher.reviewerId }}）</strong><small>{{ teacher.college }} · {{ teacher.direction }}</small><small>课时待审 {{ teacher.pendingCount }} 项 · 申诉待复审 {{ teacher.appealPendingCount }} 项</small></span></label></div></section><div class="actions"><button @click="back">返回</button><button class="assign" :disabled="!pending" @click="assign">确认分配</button></div></template><section v-else class="card empty">申诉不存在。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,920px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.wide{grid-column:1/-1}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.files{display:grid;gap:10px}.files article{display:flex;justify-content:space-between;padding:13px;background:#f8fafc}.files small,.reviewers small{display:block;color:#64748b}.files button,.actions button{padding:8px 12px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff}.reviewers{display:grid;gap:10px}.reviewers label{display:flex;gap:12px;padding:14px;border:1px solid #e2e8f0;border-radius:10px}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button{padding:10px 18px}.actions .assign{color:#fff;background:#2563eb}.actions button:disabled{opacity:.5}.empty{text-align:center}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.files article{flex-direction:column}}</style>
