<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getOperationRecord, getOperationRecords } from '../api/recordApi.js'
import { adaptRecordEnvelope, adaptRecordList } from '../adapters/recordAdapter.js'

const keyword = ref(''); const reviewType = ref(''); const result = ref(''); const selected = ref(null)
const allRecords = ref([])
const resultText = (value) => ({ approved: '通过', modified_approved: '修改课时并通过', rejected: '驳回', re_review_approved: '复审通过', re_review_rejected: '复审驳回' }[value] || value || '--')
function toReviewerItem(record) { const appeal=String(record.targetType||record.type||'').toLowerCase().includes('appeal');const target=record.target??{};return {...record,key:`record-${record.id}`,reviewType:appeal?'appeal':'normal',reviewTypeText:appeal?'申诉复审':'普通审核',studentName:record.person,sourceText:appeal?'学生课时认定申诉':record.targetType||'课时申请',requestedHours:target.requested_hours??target.original_final_hours,hours:target.review_hours??target.recognized_hours??target.final_hours,result:record.result,comment:record.comment||'--',reviewTime:record.time,status:record.status} }
const allItems = computed(() => allRecords.value.map(toReviewerItem))

const items = computed(() => {
  const search = keyword.value.trim().toLowerCase()
  return allItems.value.filter((item) => (!reviewType.value || item.reviewType === reviewType.value)
    && (!result.value || item.result === result.value)
    && (!search || item.studentName.toLowerCase().includes(search) || item.title.toLowerCase().includes(search)))
})
async function openDetail(item) { try { selected.value=toReviewerItem(adaptRecordEnvelope(await getOperationRecord(item.id))) } catch(error) { window.alert(error?.message||'审核记录详情加载失败') } }
onMounted(async()=>{try{allRecords.value=adaptRecordList(await getOperationRecords({role_scope:'reviewer',page:1,page_size:100}))}catch(error){window.alert(error?.message||'审核记录加载失败')}})
</script>

<template><main class="record-page"><div class="page-content">
  <header class="page-header"><div><p class="eyebrow">MY REVIEW RECORDS</p><h1>我的审核记录</h1><p>查看课时认定材料审核与申诉复审历史，不包含队长上传的项目成果确认。</p></div><RouterLink class="back-link" to="/reviewer/dashboard">返回审核首页</RouterLink></header>
  <section class="filters"><label><span>审核类型</span><select v-model="reviewType"><option value="">全部</option><option value="normal">普通审核</option><option value="appeal">申诉复审</option></select></label><label><span>审核结果</span><select v-model="result"><option value="">全部结果</option><option value="approved">通过</option><option value="modified_approved">修改课时并通过</option><option value="rejected">驳回</option><option value="re_review_approved">复审通过</option><option value="re_review_rejected">复审驳回</option></select></label><label><span>搜索</span><input v-model="keyword" type="search" placeholder="搜索学生姓名或申请名称" /></label></section>
  <section class="list-panel"><div class="panel-header"><h2>审核记录</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrapper"><table><thead><tr><th>记录编号</th><th>审核类型</th><th>关联申请名称</th><th>学生姓名</th><th>申请 / 申诉来源</th><th>申请 / 原认定 / 复审课时</th><th>审核结果</th><th>审核意见</th><th>审核时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.key"><td>{{ item.id }}</td><td>{{ item.reviewTypeText }}</td><td>{{ item.title }}</td><td>{{ item.studentName }}</td><td>{{ item.sourceText }}</td><td>{{ item.hours ?? item.requestedHours ?? '--' }} 课时</td><td><StatusTag :status="item.result" :text="resultText(item.result)" /></td><td class="comment">{{ item.comment }}</td><td>{{ item.reviewTime }}</td><td><StatusTag :status="item.status" /></td><td><button class="detail-link" @click="openDetail(item)">查看详情</button></td></tr><tr v-if="!items.length"><td class="empty" colspan="11">暂无审核记录</td></tr></tbody></table></div></section>

  <div v-if="selected" class="modal-mask" @click.self="selected = null"><section class="modal"><header><div><p class="eyebrow">REVIEW RECORD DETAIL</p><h2>{{ selected.reviewTypeText }}详情</h2></div><button @click="selected = null">关闭</button></header>
    <section class="detail-section"><h3>处理记录与关联业务</h3><dl class="detail-grid"><div><dt>记录编号</dt><dd>{{ selected.id }}</dd></div><div><dt>关联业务编号</dt><dd>{{ selected.targetId || '--' }}</dd></div><div><dt>关联申请名称</dt><dd>{{ selected.title }}</dd></div><div><dt>学生姓名</dt><dd>{{ selected.studentName }}</dd></div><div><dt>审核类型</dt><dd>{{ selected.reviewTypeText }}</dd></div><div><dt>审核结果</dt><dd>{{ resultText(selected.result) }}</dd></div><div><dt>处理前状态</dt><dd><StatusTag :status="selected.beforeStatus" /></dd></div><div><dt>处理后状态</dt><dd><StatusTag :status="selected.afterStatus" /></dd></div><div><dt>审核时间</dt><dd>{{ selected.reviewTime }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="selected.status" /></dd></div><div class="wide"><dt>审核意见</dt><dd>{{ selected.comment }}</dd></div><div v-for="(value, label) in selected.detail" :key="label"><dt>{{ label }}</dt><dd>{{ value ?? '--' }}</dd></div></dl></section>
    <div class="modal-actions"><button @click="selected = null">返回</button></div></section></div>
</div></main></template>

<style scoped>.record-page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.page-content{width:min(100%,1380px);margin:auto}.page-header,.modal header{display:flex;justify-content:space-between;gap:24px;margin-bottom:24px}.page-header h1,.modal h2{margin:0 0 8px}.page-header p{color:#64748b}.eyebrow{margin:0 0 7px!important;color:#2563eb!important;font-size:12px;font-weight:800}.back-link{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;background:#fff;font-weight:700;text-decoration:none}.reviewer-switcher,.filters{margin-bottom:16px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.reviewer-switcher{border-color:#bfdbfe;background:#eff6ff}.reviewer-switcher span,.filters span{display:block;margin-bottom:7px;font-weight:700}.reviewer-switcher select,.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}.filters{display:grid;grid-template-columns:220px 260px 1fr;gap:16px}.list-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-header{display:flex;justify-content:space-between;padding:18px 20px}.panel-header h2{margin:0}.panel-header span{color:#64748b}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}.comment{max-width:220px;overflow:hidden;text-overflow:ellipsis}.detail-link{border:0;color:#2563eb;background:none;font-weight:700;cursor:pointer}.empty{text-align:center;color:#64748b}.modal-mask{position:fixed;inset:0;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.5);z-index:30}.modal{width:min(100%,900px);max-height:90vh;overflow:auto;padding:24px;border-radius:16px;background:#fff}.modal header>button,.modal-actions button,.files button{padding:8px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.detail-section{margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:12px}.detail-section h3{margin-top:0}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.detail-grid .wide{grid-column:1/-1}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.files{display:grid;gap:9px}.files article{display:flex;justify-content:space-between;gap:12px;padding:12px;background:#f8fafc}.files small{display:block;color:#64748b}.modal-actions{text-align:right}@media(max-width:760px){.record-page{padding:24px 14px}.page-header,.files article{flex-direction:column}.filters,.detail-grid{grid-template-columns:1fr}.detail-grid .wide{grid-column:auto}}</style>
