<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { currentReviewerId, getApplications, mockReviewers } from '../mock/applications.js'
const result = ref(''); const keyword = ref('')
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return getApplications().filter((item) => item.reviewerId === currentReviewerId.value && item.reviewStatus && item.reviewStatus !== 'pending' && (!result.value || item.reviewStatus === result.value) && (!search || item.studentName.toLowerCase().includes(search) || item.title.toLowerCase().includes(search))) })
</script>
<template><main class="record-page"><div class="page-content"><header class="page-header"><div><p class="eyebrow">MY REVIEW RECORDS</p><h1>我的审核记录</h1><p>查看当前审核老师已经处理的历史记录。</p></div><RouterLink class="back-link" to="/reviewer/dashboard">返回审核首页</RouterLink></header><section class="reviewer-switcher"><label for="record-reviewer"><span>当前审核老师</span><select id="record-reviewer" v-model="currentReviewerId"><option v-for="reviewer in mockReviewers" :key="reviewer.reviewerId" :value="reviewer.reviewerId">{{ reviewer.reviewerName }}｜{{ reviewer.college }}｜{{ reviewer.direction }}｜待审核 {{ reviewer.pendingCount }} 条</option></select></label></section><section class="filters"><label><span>审核结果</span><select v-model="result"><option value="">全部结果</option><option value="approved">审核通过</option><option value="modified_approved">修改课时后审核通过</option><option value="rejected">已驳回</option></select></label><label><span>搜索</span><input v-model="keyword" type="search" placeholder="搜索学生姓名或任务标题" /></label></section><section class="list-panel"><div class="panel-header"><h2>审核记录</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrapper"><table><thead><tr><th>任务 / 申请标题</th><th>学生姓名</th><th>申请类型</th><th>申请来源</th><th>认定课时</th><th>审核结果</th><th>审核时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ item.title }}</strong><small>{{ item.id }}</small></td><td>{{ item.studentName }}</td><td>{{ item.applyTypeText }}</td><td>{{ item.sourceText }}</td><td>{{ item.recognizedHours }} 小时</td><td><StatusTag :status="item.reviewStatus" :text="item.reviewStatus === 'modified_approved' ? '修改课时后审核通过' : item.reviewStatus === 'approved' ? '审核通过' : '已驳回'" /></td><td>{{ item.reviewTime }}</td><td><RouterLink class="detail-link" :to="`/reviewer/review-records/${item.id}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td class="empty" colspan="8">当前审核老师暂无审核记录。</td></tr></tbody></table></div></section></div></main></template>
<style scoped>
.record-page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.page-content{width:min(100%,1140px);margin:0 auto}.page-header{display:flex;justify-content:space-between;gap:24px;margin-bottom:24px}.page-header h1{margin:0 0 8px}.page-header p{color:#64748b}.back-link,.detail-link{color:#2563eb;font-weight:700;text-decoration:none}.back-link{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.reviewer-switcher{margin-bottom:16px;padding:18px;border:1px solid #bfdbfe;border-radius:14px;background:#eff6ff}.reviewer-switcher span,.filters span{display:block;margin-bottom:7px;font-weight:700}.reviewer-switcher select{width:100%;padding:11px;border:1px solid #93c5fd;border-radius:8px;background:#fff;font:inherit}.filters{display:grid;grid-template-columns:260px 1fr;gap:16px;margin-bottom:20px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.list-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-header{display:flex;justify-content:space-between;padding:18px 20px}.panel-header h2{margin:0}.panel-header span{color:#64748b}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}td small{display:block;color:#94a3b8}.empty{text-align:center;color:#64748b}@media(max-width:680px){.record-page{padding:24px 14px}.page-header{flex-direction:column}.filters{grid-template-columns:1fr}}
</style>
