<script setup>
import { computed,onMounted,ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getReviewerAppeals } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
const APPEAL_STATUS={PENDING_RE_REVIEW:'pending_reviewer_review'};const keyword=ref('');const status=ref('pending_reviewer_review');const remoteItems=ref([])
onMounted(async()=>{try{remoteItems.value=adaptAppealList(await getReviewerAppeals({page_size:100}))}catch(error){window.alert(error?.message||'申诉复审列表加载失败')}})
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter((item)=>(!status.value||item.reopenStage===status.value)&&(!search||[item.studentName,item.applicationTitle].some((value)=>String(value||'').toLowerCase().includes(search))))})
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">R201 · APPEAL RE-REVIEW</p><h1>申诉复审</h1><p>查看分配给当前审核老师的申诉复审任务。</p></div><RouterLink class="back" to="/reviewer/dashboard">返回审核首页</RouterLink></header><nav class="tabs"><RouterLink to="/reviewer/review-tasks">项目成果审核</RouterLink><RouterLink class="active" to="/reviewer/appeal-reviews">申诉复审</RouterLink></nav><section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或申请名称" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option :value="APPEAL_STATUS.PENDING_RE_REVIEW">等待复审</option></select></label></section><section class="panel"><div class="head"><h2>待复审申诉</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>申诉编号</th><th>关联申请名称</th><th>学生姓名</th><th>原申请状态</th><th>原认定课时</th><th>管理员分配时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.studentName }}</td><td><StatusTag :status="item.originalStatus" /></td><td>{{ item.originalFinalHours }} 课时</td><td>{{ item.reviewAssignTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink :to="`/reviewer/appeal-reviews/${item.appealId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="8" class="empty">暂无待复审申诉</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1250px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.tabs{display:flex;gap:8px;margin-bottom:18px;padding:6px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.tabs a{padding:10px 16px;border-radius:8px;color:#475569;text-decoration:none;font-weight:700}.tabs .active{color:#1d4ed8;background:#dbeafe}.filters{display:grid;grid-template-columns:1fr 300px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}}</style>
