<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { currentReviewerId, getApplications, mockReviewers } from '../mock/applications.js'
import { getAppeals } from '../mock/appeals.js'

const keyword = ref('')
const reviewType = ref('')
const status = ref('')
const finishedAppealStatuses = new Set(['re_review_approved', 're_review_rejected', 'final_confirmed'])
const allItems = computed(() => [
  ...getApplications().filter((item) => item.reviewerId === currentReviewerId.value && item.reviewStatus && item.reviewStatus !== 'pending').map((item) => ({ key: `normal-${item.id}`, id: item.id, reviewType: 'normal', reviewTypeText: '普通审核', title: item.title, studentName: item.studentName, sourceText: item.sourceText, hours: item.recognizedHours, status: item.reviewStatus, reviewTime: item.reviewTime, detailTo: `/reviewer/review-records/${item.id}` })),
  ...getAppeals().filter((item) => item.reviewTeacherId === currentReviewerId.value && finishedAppealStatuses.has(item.status)).map((item) => ({ key: `appeal-${item.appealId}`, id: item.appealId, reviewType: 'appeal', reviewTypeText: '申诉复审', title: item.applicationTitle, studentName: item.studentName, sourceText: '学生课时认定申诉', hours: item.reviewHours ?? item.originalFinalHours, status: item.status, reviewTime: item.reviewTime, detailTo: `/reviewer/appeal-reviews/${item.appealId}?from=records` })),
])
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return allItems.value.filter((item) => (!reviewType.value || item.reviewType === reviewType.value) && (!status.value || item.status === status.value) && (!search || item.studentName.toLowerCase().includes(search) || item.title.toLowerCase().includes(search))) })
</script>
<template><main class="record-page"><div class="page-content">
  <header class="page-header"><div><p class="eyebrow">MY REVIEW RECORDS</p><h1>我的审核记录</h1><p>统一查看普通课时申请审核与申诉复审历史记录。</p></div><RouterLink class="back-link" to="/reviewer/dashboard">返回审核首页</RouterLink></header>
  <section class="reviewer-switcher"><label><span>当前审核老师</span><select v-model="currentReviewerId"><option v-for="reviewer in mockReviewers" :key="reviewer.reviewerId" :value="reviewer.reviewerId">{{ reviewer.reviewerName }} · {{ reviewer.college }} · {{ reviewer.direction }}</option></select></label></section>
  <section class="filters"><label><span>审核类型</span><select v-model="reviewType"><option value="">全部</option><option value="normal">普通审核</option><option value="appeal">申诉复审</option></select></label><label><span>审核结果</span><select v-model="status"><option value="">全部结果</option><option value="approved">审核通过</option><option value="modified_approved">修改课时后通过</option><option value="rejected">已驳回</option><option value="re_review_approved">复审通过</option><option value="re_review_rejected">复审驳回</option><option value="final_confirmed">管理员已最终确认</option></select></label><label><span>搜索</span><input v-model="keyword" type="search" placeholder="搜索学生姓名或申请名称" /></label></section>
  <section class="list-panel"><div class="panel-header"><h2>审核记录</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrapper"><table><thead><tr><th>编号</th><th>审核类型</th><th>关联申请名称</th><th>学生姓名</th><th>来源</th><th>认定 / 复审课时</th><th>审核结果</th><th>审核时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.key"><td>{{ item.id }}</td><td>{{ item.reviewTypeText }}</td><td>{{ item.title }}</td><td>{{ item.studentName }}</td><td>{{ item.sourceText }}</td><td>{{ item.hours ?? '--' }} 课时</td><td><StatusTag :status="item.status" /></td><td>{{ item.reviewTime || '--' }}</td><td><RouterLink class="detail-link" :to="item.detailTo">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td class="empty" colspan="9">当前审核老师暂无审核记录。</td></tr></tbody></table></div></section>
</div></main></template>
<style scoped>.record-page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.page-content{width:min(100%,1200px);margin:auto}.page-header{display:flex;justify-content:space-between;gap:24px;margin-bottom:24px}.page-header h1{margin:0 0 8px}.page-header p{color:#64748b}.eyebrow{margin:0 0 7px!important;color:#2563eb!important;font-size:12px;font-weight:800}.back-link,.detail-link{color:#2563eb;font-weight:700;text-decoration:none}.back-link{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.reviewer-switcher,.filters{margin-bottom:16px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.reviewer-switcher{border-color:#bfdbfe;background:#eff6ff}.reviewer-switcher span,.filters span{display:block;margin-bottom:7px;font-weight:700}.reviewer-switcher select,.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}.filters{display:grid;grid-template-columns:220px 260px 1fr;gap:16px}.list-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-header{display:flex;justify-content:space-between;padding:18px 20px}.panel-header h2{margin:0}.panel-header span{color:#64748b}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}.empty{text-align:center;color:#64748b}@media(max-width:760px){.record-page{padding:24px 14px}.page-header{flex-direction:column}.filters{grid-template-columns:1fr}}</style>
