<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { currentReviewerId, getReviewerPendingApplications } from '../mock/applications.js'
const type = ref(''); const keyword = ref('')
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return getReviewerPendingApplications().filter((item) => item.reviewerId === currentReviewerId && (!type.value || item.applyType === type.value) && (!search || item.studentName.toLowerCase().includes(search) || item.title.toLowerCase().includes(search))) })
</script>
<template><main class="review-page"><div class="page-content"><header class="page-header"><div><p class="eyebrow">REVIEW TASKS</p><h1>待审核任务</h1><p>处理管理员已受理的课时申请。</p></div><RouterLink class="back-link" to="/reviewer/dashboard">返回审核首页</RouterLink></header><section class="filters"><label><span>申请类型</span><select v-model="type"><option value="">全部类型</option><option value="with_result">有成果申请</option><option value="without_result">无成果申请</option></select></label><label><span>搜索</span><input v-model="keyword" type="search" placeholder="搜索学生姓名或任务标题" /></label></section><section class="list-panel"><div class="panel-header"><h2>待审核列表</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrapper"><table><thead><tr><th>任务 / 申请标题</th><th>学生姓名</th><th>申请类型</th><th>申请来源</th><th>申请课时</th><th>指导老师</th><th>分配审核老师</th><th>管理员受理时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ item.title }}</strong><small>{{ item.id }}</small></td><td>{{ item.studentName }}</td><td>{{ item.applyTypeText }}</td><td>{{ item.sourceText }}</td><td>{{ item.requestedHours }} 小时</td><td>{{ item.mainAdvisor?.name || '--' }}</td><td>{{ item.reviewer?.name || '--' }}</td><td>{{ item.adminAcceptTime }}</td><td><StatusTag :status="item.status" text="待审核" /></td><td><RouterLink class="detail-link" :to="`/reviewer/review-tasks/${item.id}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td class="empty" colspan="10">暂无符合条件的待审核任务。</td></tr></tbody></table></div></section></div></main></template>
<style scoped>
.review-page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.page-content{width:min(100%,1180px);margin:0 auto}.page-header{display:flex;justify-content:space-between;gap:24px;margin-bottom:24px}.page-header h1{margin:0 0 8px}.page-header p{color:#64748b}.back-link,.detail-link{color:#2563eb;font-weight:700;text-decoration:none}.back-link{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.filters{display:grid;grid-template-columns:260px 1fr;gap:16px;margin-bottom:20px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.list-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-header{display:flex;justify-content:space-between;padding:18px 20px}.panel-header h2{margin:0;font-size:19px}.panel-header span{color:#64748b}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}td small{display:block;color:#94a3b8}.empty{text-align:center;color:#64748b}@media(max-width:680px){.review-page{padding:24px 14px}.page-header{flex-direction:column}.filters{grid-template-columns:1fr}}
</style>
