<script setup>
import { computed, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { addComplaint } from '../mock/complaints.js'
import { getApplications } from '../mock/applications.js'
const router = useRouter(); const student = { studentId: '2024001', studentName: '张三' }
const types = ['流程问题', '材料问题', '处理结果问题', '人员沟通问题', '其他问题']
const form = reactive({ complaintType: '', relateApplication: false, applicationId: '', content: '', files: [] })
const applications = computed(() => getApplications().filter((item) => item.studentId === student.studentId))
const selected = computed(() => applications.value.find((item) => item.id === form.applicationId))
function nowText() { return new Date().toLocaleString('zh-CN', { hour12: false }).replaceAll('/', '-') }
function sizeText(bytes) { if (bytes >= 1048576) return `${(bytes / 1048576).toFixed(2)} MB`; if (bytes >= 1024) return `${(bytes / 1024).toFixed(2)} KB`; return `${bytes} B` }
function selectFiles(event) { Array.from(event.target.files || []).forEach((file, index) => form.files.push({ id: `CMP-ATT-${Date.now()}-${index}`, fileName: file.name, fileType: file.type || '未知类型', fileSize: sizeText(file.size), uploadTime: nowText(), mockUrl: URL.createObjectURL(file) })); event.target.value = '' }
function removeFile(id) { const index = form.files.findIndex((item) => item.id === id); if (index < 0) return; if (form.files[index].mockUrl) URL.revokeObjectURL(form.files[index].mockUrl); form.files.splice(index, 1) }
function preview() { window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。') }
function download() { window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。') }
function submit() { if (!form.complaintType) return window.alert('请选择投诉类型。'); if (form.relateApplication && !selected.value) return window.alert('请选择关联课时申请。'); if (!form.content.trim()) return window.alert('请填写投诉内容。'); const complaint = addComplaint({ ...student, isAnonymous: true, relatedApplicationId: selected.value?.id || '', relatedApplicationTitle: selected.value?.title || '', complaintType: form.complaintType, complaintContent: form.content, complaintMaterials: form.files }); if (!complaint) return window.alert('投诉提交失败。'); window.alert('匿名投诉已提交，等待管理员处理。'); router.push(`/student/complaints/submitted/${complaint.complaintId}`) }
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">S801 · ANONYMOUS COMPLAINT</p><h1>发起匿名投诉</h1><p>投诉仅用于问题反馈，不会改变课时申请或其他业务状态。</p></div><RouterLink to="/student/feedback">返回问题反馈</RouterLink></header>
<section class="notice"><strong>匿名提示</strong><p>本次投诉默认匿名提交，管理员处理页面不会展示你的姓名和学号。</p></section>
<section class="card"><label>投诉类型</label><select v-model="form.complaintType"><option value="">请选择投诉类型</option><option v-for="type in types" :key="type">{{ type }}</option></select><label class="check"><input v-model="form.relateApplication" type="checkbox" />关联具体课时申请</label><select v-if="form.relateApplication" v-model="form.applicationId"><option value="">请选择课时申请</option><option v-for="item in applications" :key="item.id" :value="item.id">{{ item.title }} · {{ item.id }}</option></select></section>
<section class="card"><h2>投诉内容</h2><textarea v-model="form.content" rows="7" placeholder="请详细说明需要反馈的问题"></textarea></section>
<section class="card"><h2>投诉材料（可选）</h2><p class="muted">当前为 Mock 上传，仅保存文件信息，不会上传到服务器。</p><input type="file" multiple @change="selectFiles" /><div class="files"><article v-for="file in form.files" :key="file.id"><div><strong>{{ file.fileName }}</strong><small>{{ file.fileType }} · {{ file.fileSize }} · {{ file.uploadTime }}</small></div><div><button @click="preview(file)">预览</button><button @click="download">下载</button><button class="remove" @click="removeFile(file.id)">删除</button></div></article></div></section>
<div class="actions"><RouterLink to="/student/feedback">返回</RouterLink><button @click="submit">提交匿名投诉</button></div></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,900px);margin:auto}header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}header a,.actions a{color:#2563eb;font-weight:700;text-decoration:none}.notice,.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.notice{border-color:#bfdbfe;background:#eff6ff}.notice p{margin-bottom:0;color:#475569}.card h2{margin-top:0}.card>label{display:block;margin:16px 0 8px;font-weight:700}.card>label:first-child{margin-top:0}.card .check{display:flex;align-items:center;gap:8px}select,textarea,input[type=file]{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.muted{color:#64748b}.files{display:grid;gap:9px;margin-top:14px}.files article{display:flex;justify-content:space-between;gap:12px;padding:13px;background:#f8fafc}.files small{display:block;color:#64748b}.files button{margin-left:6px;color:#2563eb}.files .remove{color:#b91c1c}.actions{display:flex;justify-content:flex-end;gap:10px}.actions a,.actions>button{padding:10px 16px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.actions>button{border-color:#2563eb;color:#fff;background:#2563eb;font-weight:700}@media(max-width:650px){header,.files article{flex-direction:column}}</style>
