<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { getComplaintById } from '../mock/complaints.js'
const route = useRoute(); const studentId = '2024001'; const complaint = computed(() => { const item = getComplaintById(route.params.id); return item?.studentId === studentId ? item : null })
</script>
<template><main class="page"><section v-if="complaint" class="result"><div class="icon">✓</div><h1>投诉提交成功</h1><p>匿名投诉已提交至管理员端，请等待处理。</p><dl><div><dt>投诉编号</dt><dd>{{ complaint.complaintId }}</dd></div><div><dt>提交时间</dt><dd>{{ complaint.submitTime }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="complaint.status" /></dd></div></dl><div class="actions"><RouterLink to="/student/feedback">返回问题反馈首页</RouterLink><RouterLink class="primary" to="/student/dashboard">返回学生首页</RouterLink></div></section><section v-else class="result"><h1>未找到投诉记录</h1><RouterLink to="/student/feedback">返回问题反馈首页</RouterLink></section></main></template>
<style scoped>.page{min-height:100vh;display:grid;place-items:center;padding:24px;background:#f3f6fb}.result{width:min(100%,620px);padding:38px;border:1px solid #e2e8f0;border-radius:18px;background:#fff;text-align:center}.icon{display:grid;place-items:center;width:58px;height:58px;margin:0 auto 18px;border-radius:50%;color:#fff;background:#16a34a;font-size:30px}.result h1{margin:0 0 10px}.result>p{color:#64748b}dl{margin:26px 0;text-align:left}dl div{display:flex;justify-content:space-between;gap:20px;padding:13px;border-bottom:1px solid #e2e8f0}dt{color:#64748b}dd{margin:0;font-weight:700}.actions{display:flex;justify-content:center;gap:10px}.actions a,.result>a{padding:10px 15px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;text-decoration:none;font-weight:700}.actions .primary{border-color:#2563eb;color:#fff;background:#2563eb}@media(max-width:560px){.actions{flex-direction:column}}</style>
