<script setup>
import { computed, reactive } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { addAppeal, getAppealableApplications } from '../mock/appeals.js'
const route=useRoute();const router=useRouter();const student={studentId:'2024001',name:'张三'}
const form=reactive({applicationId:String(route.query.applicationId||''),reason:'',files:[]})
const applications=computed(()=>getAppealableApplications(student.studentId));const selected=computed(()=>applications.value.find((item)=>item.id===form.applicationId))
function nowText(){return new Date().toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-')};function sizeText(bytes){if(bytes>=1048576)return`${(bytes/1048576).toFixed(2)} MB`;if(bytes>=1024)return`${(bytes/1024).toFixed(2)} KB`;return`${bytes} B`}
function selectFiles(event){Array.from(event.target.files||[]).forEach((file,index)=>form.files.push({id:`APL-ATT-${Date.now()}-${index}`,name:file.name,type:file.type||'未知类型',size:sizeText(file.size),uploadedAt:nowText(),mockUrl:URL.createObjectURL(file)}));event.target.value=''}
function removeFile(id){const file=form.files.find((item)=>item.id===id);if(file?.mockUrl)URL.revokeObjectURL(file.mockUrl);form.files.splice(form.files.findIndex((item)=>item.id===id),1)}
function submit(){if(!selected.value)return window.alert('请选择一条可申诉的课时申请。');if(!form.reason.trim())return window.alert('请填写申诉原因。');const appeal=addAppeal({applicationId:selected.value.id,studentId:student.studentId,studentName:student.name,appealReason:form.reason,appealMaterials:form.files});if(!appeal)return window.alert('申诉提交失败，该申请可能已有进行中的申诉。');window.alert('申诉已提交，等待管理员处理。');router.push('/student/appeals')}
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">S701 · CREATE APPEAL</p><h1>发起申诉</h1><p>选择已有明确处理结果的课时申请。</p></div><RouterLink to="/student/feedback">返回问题反馈</RouterLink></header><section class="card"><label>可申诉申请</label><select v-model="form.applicationId"><option value="">请选择课时申请</option><option v-for="item in applications" :key="item.id" :value="item.id">{{ item.title }} · {{ item.id }}</option></select><p v-if="!applications.length" class="muted">暂无可申诉的课时申请。</p></section><section v-if="selected" class="card"><h2>原申请信息</h2><dl class="grid"><div><dt>申请名称</dt><dd>{{ selected.title }}</dd></div><div><dt>申请状态</dt><dd><StatusTag :status="selected.status" /></dd></div><div><dt>原认定课时</dt><dd>{{ selected.recognizedHours??selected.requestedHours }} 课时</dd></div><div><dt>原处理意见</dt><dd>{{ selected.finalComment||selected.reviewComment||selected.advisorComment||'--' }}</dd></div></dl></section><section class="card"><h2>申诉原因</h2><textarea v-model="form.reason" rows="6" placeholder="请详细说明申诉理由。"></textarea></section><section class="card"><h2>申诉材料</h2><input type="file" multiple @change="selectFiles" /><div class="files"><article v-for="file in form.files" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size }} · {{ file.uploadedAt }}</small></div><button @click="removeFile(file.id)">删除</button></article></div></section><div class="actions"><RouterLink to="/student/feedback">返回</RouterLink><button @click="submit">提交申诉</button></div></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,900px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.card label{display:block;margin-bottom:8px;font-weight:700}select,textarea,input[type=file]{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}dt,.muted{color:#64748b}dd{margin:5px 0 0;font-weight:600}.files{display:grid;gap:9px;margin-top:14px}.files article{display:flex;justify-content:space-between;padding:13px;background:#f8fafc}.files small{display:block;color:#64748b}.files button{color:#b91c1c}.actions{display:flex;justify-content:flex-end;gap:10px}.actions a,.actions button,header a{padding:10px 16px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;background:#fff;font-weight:700;text-decoration:none}.actions button{color:#fff;background:#2563eb}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style>
