<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { TASK_TYPE_OPTIONS, getTaskTypeText } from '../mock/tasks.js'
import { getStudentTasks, registerTask } from '../api/taskApi.js'
import { adaptTaskList } from '../adapters/taskAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const keyword=ref('');const selectedType=ref('');const registrationStatus=ref('');const version=ref(0)
const visibleStatuses=['published','registration_open','selection_pending']
const registerableStatuses=['published','registration_open']
function isApplied(task){version.value;return Boolean(task.myRegistration)}
function canRegister(task){return registerableStatuses.includes(task.status)}
function derivedStatus(task){if(isApplied(task))return'applied';if(!canRegister(task))return'closed';return'available'}
function loadErrorMessage(error){if(error?.status===401)return'登录已过期，请重新登录';if(error?.status===403)return'无权限查看任务广场';return'任务广场加载失败'}
const remoteItems=ref([]);async function loadItems(){try{const payload=await getStudentTasks({page_size:100});remoteItems.value=adaptTaskList(payload);console.info('[task-square] task statuses:',remoteItems.value.map(item=>({id:item.id,status:item.status})))}catch(error){remoteItems.value=[];window.alert(loadErrorMessage(error))}}onMounted(loadItems)
const items=computed(()=>{version.value;const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter(item=>visibleStatuses.includes(item.status)).filter(item=>(!selectedType.value||item.taskTypeId===selectedType.value)&&(!registrationStatus.value||derivedStatus(item)===registrationStatus.value)&&(!search||item.title.toLowerCase().includes(search))).sort((a,b)=>String(a.registrationDeadline).localeCompare(String(b.registrationDeadline)))})
async function apply(item){try{await registerTask(item.id,{remark:''});window.alert('报名成功');await loadItems()}catch(error){if(error?.status===409||error?.code===40901)return window.alert('报名已截止');window.alert(getApiErrorMessage(error,'报名失败'))}}
function summary(text){const value=String(text||'暂无要求');return value.length>42?`${value.slice(0,42)}…`:value}
</script>
<template><main class="page"><div class="content"><header class="header"><div><p class="eyebrow">S201 · TASK SQUARE</p><h1>任务广场</h1><p>浏览管理员已确认发布的任务，并在截止时间前报名。</p></div><RouterLink class="back" to="/student/dashboard">返回学生首页</RouterLink></header>
<section class="filters"><label><span>任务名称</span><input v-model="keyword" type="search" placeholder="搜索任务名称" /></label><label><span>任务类型</span><select v-model="selectedType"><option value="">全部类型</option><option v-for="option in TASK_TYPE_OPTIONS" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label><span>报名状态</span><select v-model="registrationStatus"><option value="">全部状态</option><option value="available">可报名</option><option value="applied">已报名</option><option value="closed">报名已截止</option></select></label></section>
<section class="panel"><div class="panel-head"><h2>可见任务</h2><span>共 {{ items.length }} 个</span></div><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>任务类型</th><th>指导老师</th><th>报名截止时间</th><th>成果要求摘要</th><th>附件数量</th><th>是否可报名</th><th>我的报名状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ item.title }}</strong><small>{{ item.taskNo||item.id }}</small></td><td>{{ getTaskTypeText(item.taskType) }}</td><td>{{ item.advisorName }}</td><td>{{ item.registrationDeadline }}</td><td class="summary">{{ summary(item.resultRequirement) }}</td><td>{{ item.attachments?.length||0 }}</td><td><StatusTag :status="canRegister(item)?'published':'closed'" :text="canRegister(item)?'可报名':'不可报名'" /></td><td><StatusTag :status="isApplied(item)?'confirmed':'pending'" :text="isApplied(item)?'已报名':'未报名'" /></td><td><div class="actions"><RouterLink :to="`/student/task-square/${item.id}`">查看详情</RouterLink><button :disabled="!canRegister(item)||isApplied(item)" @click="apply(item)">{{ isApplied(item)?'已报名':canRegister(item)?'我要报名':'不可报名' }}</button></div></td></tr><tr v-if="!items.length"><td class="empty" colspan="9">暂无可报名任务</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1380px);margin:auto}.header,.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.header{margin-bottom:20px}.header h1{margin:0 0 8px}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.back,.actions a{color:#2563eb;font-weight:700;text-decoration:none}.back{padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.filters{display:grid;grid-template-columns:1fr 260px 260px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}td small{display:block;margin-top:4px;color:#94a3b8}.summary{max-width:300px;white-space:normal;line-height:1.6}.actions{display:flex;align-items:center;gap:10px}.actions button{padding:7px 11px;border:0;border-radius:8px;color:#fff;background:#2563eb;font:inherit;font-weight:700;cursor:pointer}.actions button:disabled{color:#64748b;background:#e2e8f0;cursor:not-allowed}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:800px){.page{padding:24px 14px}.header{flex-direction:column}.filters{grid-template-columns:1fr}}</style>
