<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { getTaskTypeText } from '../mock/tasks.js'
import { getStudentTask, registerTask } from '../api/taskApi.js'
import { adaptTaskEnvelope } from '../adapters/taskAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const route=useRoute();const router=useRouter();const version=ref(0);const task=ref(null)
async function loadTask(){try{task.value=adaptTaskEnvelope(await getStudentTask(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'任务详情加载失败'))}}onMounted(loadTask)
const closed=computed(()=>{const time=new Date(String(task.value?.registrationDeadline||'').replace(' ','T')).getTime();return !Number.isFinite(time)||Date.now()>=time})
const applied=computed(()=>Boolean(task.value?.myRegistration))
async function apply(){try{await registerTask(task.value.id,{remark:''});window.alert('报名成功');await loadTask()}catch(error){if(error?.status===409||error?.code===40901)return window.alert(closed.value?'报名已截止':'当前状态已变化，请刷新后重试');window.alert(getApiErrorMessage(error,'报名失败'))}}
function back(){router.push('/student/task-square')}
function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}
function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
</script>
<template><main class="page"><div class="content"><template v-if="task"><header class="header"><div><p class="eyebrow">S202 · TASK DETAIL</p><h1>{{ task.title }}</h1><p>{{ task.taskId }}</p></div><div class="status"><StatusTag status="published" text="已发布" /><StatusTag :status="closed?'closed':'published'" :text="closed?'报名已截止':'可报名'" /></div></header>
<section class="card"><h2>任务信息</h2><dl class="grid"><div><dt>任务名称</dt><dd>{{ task.title }}</dd></div><div><dt>任务类型</dt><dd>{{ getTaskTypeText(task.taskType) }}</dd></div><div><dt>指导老师</dt><dd>{{ task.advisorName }}</dd></div><div><dt>报名截止时间</dt><dd>{{ task.registrationDeadline }}</dd></div><div class="wide"><dt>任务说明</dt><dd>{{ task.description||'--' }}</dd></div><div class="wide"><dt>报名条件</dt><dd>{{ task.requirement||'不限' }}</dd></div><div class="wide"><dt>成果提交要求</dt><dd>{{ task.resultRequirement||'--' }}</dd></div></dl></section>
<section class="card"><h2>附件材料</h2><div class="files"><article v-for="file in task.attachments" :key="file.id||file.name"><div><strong>{{ file.name }}</strong><small>文件类型：{{ file.type||'未知类型' }} · 文件大小：{{ file.size||'--' }} · 上传时间：{{ file.uploadedAt||'--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!task.attachments?.length" class="empty">暂无附件材料。</p></div></section>
<section class="card"><h2>报名状态</h2><dl class="grid"><div><dt>当前是否可报名</dt><dd><StatusTag :status="closed?'closed':'published'" :text="closed?'报名已截止':'可报名'" /></dd></div><div><dt>我的报名状态</dt><dd><StatusTag :status="applied?'confirmed':'pending'" :text="applied?'已报名，待指导老师筛选':'尚未报名'" /></dd></div></dl><p class="tip">个人报名不代表最终参与，报名后需等待指导老师筛选。</p></section>
<div class="actions"><button class="back" @click="back">返回</button><button class="apply" :disabled="closed||applied" @click="apply">{{ applied?'已报名':closed?'报名已截止':'我要报名' }}</button></div>
</template><section v-else class="card empty"><h1>未找到已发布任务</h1><p>该任务可能尚未发布或已不在任务广场展示。</p><button class="back" @click="back">返回任务广场</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,980px);margin:auto}.header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}.header h1{margin:0}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.status{display:flex;align-items:flex-start;gap:8px}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px;font-size:19px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}.wide{grid-column:1/-1}.grid dt{color:#64748b;font-size:13px}.grid dd{margin:5px 0 0;font-weight:600;line-height:1.75}.files{display:grid;gap:10px}.files article{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:14px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.files small{display:block;margin-top:5px;color:#64748b}.files article>div:last-child{display:flex;gap:8px}.files button{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#1d4ed8;background:#fff;font-weight:700;cursor:pointer}.tip{margin:18px 0 0;padding:12px;border-radius:9px;color:#475569;background:#f8fafc}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button,.empty button{padding:10px 18px;border-radius:9px;font:inherit;font-weight:700;cursor:pointer}.back{border:1px solid #cbd5e1;background:#fff}.apply{border:0;color:#fff;background:#2563eb}.apply:disabled{color:#64748b;background:#e2e8f0;cursor:not-allowed}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}.header,.files article{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.actions{flex-wrap:wrap}}</style>
