<script setup>
import { computed, reactive } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AttachmentNotice from '../components/AttachmentNotice.vue'
import StatusTag from '../components/StatusTag.vue'
import { TASK_RESULT_STATUS, addTaskResult, getTaskResultByTaskId, hasActiveTaskResult, resubmitTaskResult } from '../mock/taskResults.js'
import { getSelectedStudents, getTaskById, getTaskTypeText, markTaskResultSubmitted } from '../mock/tasks.js'

const route = useRoute(); const router = useRouter()
const currentStudent = { studentId: '2024001', name: '张三' }
const task = computed(() => getTaskById(route.params.id))
const existingResult = computed(() => getTaskResultByTaskId(route.params.id))
const isLeader = computed(() => task.value?.leaderId === currentStudent.studentId)
const isResubmit = computed(() => existingResult.value?.status === TASK_RESULT_STATUS.ADVISOR_REJECTED)
const duplicate = computed(() => hasActiveTaskResult(route.params.id) && !isResubmit.value)
const teamMembers = computed(() => task.value ? getSelectedStudents(task.value.taskId) : [])
const form = reactive({ description: existingResult.value?.resultDescription || '', requestedHours: existingResult.value?.requestedHours || '', resultFiles: [], proofFiles: [] })
function nowText() { return new Date().toLocaleString('zh-CN', { hour12: false }).replaceAll('/', '-') }
function readFiles(event, target, category) { Array.from(event.target.files || []).forEach((file, index) => target.push({ id: `RESULT-ATT-${Date.now()}-${index}`, name: file.name, type: file.type || '未知类型', size: `${file.size} B`, uploadedAt: nowText(), mockUrl: URL.createObjectURL(file), category })); event.target.value = '' }
function removeFile(target, id) { const index = target.findIndex((item) => item.id === id); if (index < 0) return; if (target[index].mockUrl) URL.revokeObjectURL(target[index].mockUrl); target.splice(index, 1) }
function validate() { if (!task.value) return '任务不存在。'; if (!isLeader.value) return '只有被指定的队长才能提交任务成果。'; if (duplicate.value) return '该任务已有成果记录，请勿重复创建。'; if (!form.description.trim()) return '请填写成果说明。'; if (!Number.isFinite(Number(form.requestedHours)) || Number(form.requestedHours) <= 0) return '申请课时必须大于 0。'; if (!form.resultFiles.length) return '请至少上传 1 个成果材料。'; return '' }
function submit() { const error = validate(); if (error) return window.alert(error); const members = teamMembers.value.map((member) => ({ id: member.studentId, name: member.studentName, studentId: member.studentId, college: member.college || '', major: member.major || '', role: member.studentId === task.value.leaderId ? 'captain' : 'member' })); const data = { taskId: task.value.taskId, taskTitle: task.value.title, taskHours: Number(form.requestedHours), requestedHours: Number(form.requestedHours), leaderId: task.value.leaderId, leaderName: task.value.leaderName, advisorId: task.value.advisorId, advisorName: task.value.advisorName, teamMembers: members, resultDescription: form.description.trim(), resultMaterials: form.resultFiles.map((file) => ({ ...file })), proofMaterials: form.proofFiles.map((file) => ({ ...file })) }; const result = isResubmit.value ? resubmitTaskResult(existingResult.value.resultId, data) : addTaskResult(data); if (!result) return window.alert('成果提交失败，请检查当前状态。'); markTaskResultSubmitted(task.value.taskId, currentStudent.studentId); window.alert(isResubmit.value ? '成果已重新提交。' : '成果已提交；真实接口会自动创建关联课时申请。'); router.push(`/student/tasks/${task.value.taskId}`) }
</script>

<template><main class="page"><div class="content"><template v-if="task"><header><div><p class="eyebrow">S105 · RESULT SUBMISSION</p><h1>{{ isResubmit ? '重新提交任务成果' : '队长上传成果' }}</h1><p>{{ task.title }} · {{ task.taskId }}</p></div><StatusTag :status="existingResult?.status || task.status" /></header><p v-if="!isLeader || duplicate" class="warning">{{ !isLeader ? '只有当前任务队长可以提交成果。' : '该任务已有成果记录，请勿重复创建。' }}</p><section class="card"><h2>任务信息</h2><dl class="grid"><div><dt>任务名称</dt><dd>{{ task.title }}</dd></div><div><dt>任务类型</dt><dd>{{ getTaskTypeText(task.taskType) }}</dd></div><div><dt>指导老师</dt><dd>{{ task.advisorName }}</dd></div><div class="wide"><dt>成果要求</dt><dd>{{ task.resultRequirement }}</dd></div></dl></section><section class="card"><h2>成果申请</h2><label>申请课时<input v-model.number="form.requestedHours" type="number" min="0.5" step="0.5" :disabled="!isLeader||duplicate" /></label><label>成果说明<textarea v-model="form.description" rows="6" :disabled="!isLeader||duplicate" /></label></section><section class="card"><h2>成果材料</h2><AttachmentNotice title="成果材料" description="首次提交或驳回重提均须重新提交附件。" :required="true" :accept-types="['PDF','Word','Excel','PPT','图片','压缩包']" /><input type="file" multiple :disabled="!isLeader||duplicate" @change="readFiles($event,form.resultFiles,'result')" /><article v-for="file in form.resultFiles" :key="file.id" class="file"><span>{{ file.name }}</span><button @click="removeFile(form.resultFiles,file.id)">删除</button></article></section><section class="card"><h2>证明材料（可选）</h2><input type="file" multiple :disabled="!isLeader||duplicate" @change="readFiles($event,form.proofFiles,'proof')" /><article v-for="file in form.proofFiles" :key="file.id" class="file"><span>{{ file.name }}</span><button @click="removeFile(form.proofFiles,file.id)">删除</button></article></section><div class="actions"><button @click="router.push(`/student/tasks/${task.taskId}`)">返回</button><button class="primary" :disabled="!isLeader||duplicate" @click="submit">{{ isResubmit ? '重新提交' : '提交成果' }}</button></div></template></div></main></template>

<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,980px);margin:auto}header{display:flex;justify-content:space-between}.eyebrow{color:#2563eb;font-size:12px;font-weight:800}.warning{padding:14px;color:#b91c1c;background:#fee2e2}.card{margin:18px 0;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.wide{grid-column:1/-1}label{display:grid;gap:8px;margin:14px 0;font-weight:700}input,textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.file{display:flex;justify-content:space-between;margin-top:10px;padding:12px;background:#f8fafc}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button,.file button{padding:9px 15px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.actions .primary{color:#fff;background:#2563eb}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
