<script setup>
import { computed } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { getAppealById } from '../mock/appeals.js'
import { getApplications } from '../mock/applications.js'
const route=useRoute();const router=useRouter();const studentId='2024001';const appeal=computed(()=>{const item=getAppealById(route.params.id);if(item?.studentId!==studentId)return null;return item.reviewTeacherName&&item.reviewAssignTime?{...item,reviewTeacherName:`${item.reviewTeacherName}（分配时间：${item.reviewAssignTime}）`}:item});const application=computed(()=>appeal.value?getApplications().find((item)=>item.id===appeal.value.applicationId):null)
function preview(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}function download(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}function back(){router.push('/student/appeals')}
</script>
<template><main class="page"><div class="content"><template v-if="appeal"><header><div><p class="eyebrow">S703 · APPEAL DETAIL</p><h1>申诉详情</h1><p>{{ appeal.appealId }}</p></div><StatusTag :status="appeal.status" /></header><section class="card"><h2>申诉基本信息</h2><dl class="grid"><div><dt>关联申请</dt><dd>{{ appeal.applicationTitle }}</dd></div><div><dt>课时申请编号</dt><dd>{{ appeal.applicationId }}</dd></div><div><dt>申诉学生</dt><dd>{{ appeal.studentName }}（{{ appeal.studentId }}）</dd></div><div><dt>提交时间</dt><dd>{{ appeal.submitTime }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="appeal.status" /></dd></div><div><dt>原处理状态</dt><dd><StatusTag :status="appeal.originalStatus" /></dd></div><div><dt>原最终课时</dt><dd>{{ appeal.originalFinalHours }} 课时</dd></div><div><dt>原处理意见</dt><dd>{{ appeal.originalComment||'--' }}</dd></div></dl></section><section class="card"><h2>申诉原因</h2><p>{{ appeal.appealReason }}</p></section><section class="card"><h2>申诉材料</h2><div class="files"><article v-for="file in appeal.appealMaterials" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><div><button @click="preview">预览</button><button @click="download">下载</button></div></article><p v-if="!appeal.appealMaterials.length">暂无附件材料</p></div></section><section class="card"><h2>处理结果</h2><dl class="grid"><div><dt>管理员处理意见</dt><dd>{{ appeal.adminComment||'待管理员处理' }}</dd></div><div><dt>管理员处理时间</dt><dd>{{ appeal.adminHandleTime||'--' }}</dd></div><div><dt>复审老师</dt><dd>{{ appeal.reviewTeacherName||'--' }}</dd></div><div><dt>复审结果</dt><dd>{{ appeal.reviewResult||'--' }}</dd></div><div><dt>最终确认结果</dt><dd>{{ appeal.finalResult||'--' }}</dd></div></dl></section><section class="card"><h2>流程时间轴</h2><ol><li v-for="step in appeal.timeline" :key="step.title"><strong>{{ step.title }}</strong><span>{{ step.time||'等待处理' }}</span><StatusTag :status="step.status==='current'?'pending':'completed'" /></li></ol></section><div class="actions"><button @click="back">返回</button></div></template><section v-else class="card">申诉不存在。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,920px);margin:auto}header{display:flex;justify-content:space-between;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.files{display:grid;gap:10px}.files article{display:flex;justify-content:space-between;padding:13px;background:#f8fafc}.files small{display:block;color:#64748b}.files button,.actions button{padding:8px 12px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff}ol{padding:0;list-style:none}li{display:grid;grid-template-columns:1fr auto auto;gap:12px;padding:12px;border-bottom:1px solid #e2e8f0}li span{color:#64748b}.actions{text-align:right}@media(max-width:650px){.grid{grid-template-columns:1fr}.files article{flex-direction:column}}</style>
