<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AttachmentNotice from '../components/AttachmentNotice.vue'
import StatusTag from '../components/StatusTag.vue'
import { getStudentApplication, submitExtensionRequest } from '../api/applicationApi.js'
import { downloadAttachment, getAttachmentErrorMessage, previewAttachment, uploadAttachment } from '../api/fileApi.js'
import { adaptApplicationEnvelope } from '../adapters/applicationAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'

const route=useRoute();const router=useRouter();const application=ref(null)
const allowed=computed(()=>application.value?.status==='pending_material'&&!application.value?.extensionApplied)
const form=reactive({newTime:'',reason:'',files:[],attachmentIds:[]})
const originalTime=computed(()=>application.value?.expectedResultDate||application.value?.originalExpectedResultTime||'')
const extensionType=computed(()=>{const original=new Date(originalTime.value);const next=new Date(form.newTime);if(Number.isNaN(original.getTime())||Number.isNaN(next.getTime())||next<=original)return'';return Math.ceil((next-original)/86400000)<=30?'normal':'special'})
const extensionDays=computed(()=>{if(!extensionType.value)return 0;return Math.ceil((new Date(`${form.newTime}T00:00:00`)-new Date(`${originalTime.value}T00:00:00`))/86400000)})
function nowText(){return new Date().toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-')}
function sizeText(bytes){if(bytes>=1048576)return`${(bytes/1048576).toFixed(2)} MB`;if(bytes>=1024)return`${(bytes/1024).toFixed(2)} KB`;return`${bytes} B`}
async function selectFiles(event){for(const file of Array.from(event.target.files||[])){try{const uploaded=await uploadAttachment(file,'hour_application');form.files.push({...uploaded.attachment,id:uploaded.id,name:file.name,type:file.type||'未知类型',size:sizeText(file.size),uploadedAt:nowText()});form.attachmentIds.push(uploaded.id)}catch(error){window.alert(getApiErrorMessage(error,'延期附件上传失败'))}}event.target.value=''}
function removeFile(id){const index=form.files.findIndex((item)=>item.id===id);if(index>=0)form.files.splice(index,1);form.attachmentIds=form.attachmentIds.filter((item)=>item!==id)}
async function preview(file){try{await previewAttachment(file)}catch(error){window.alert(getAttachmentErrorMessage(error,'preview'))}}
async function download(file){try{await downloadAttachment(file)}catch(error){window.alert(getAttachmentErrorMessage(error,'download'))}}
function back(){router.push(application.value?`/student/hour-progress/${application.value.id}`:'/student/hour-progress')}
async function loadApplication(){try{application.value=adaptApplicationEnvelope(await getStudentApplication(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'申请详情加载失败'))}}
onMounted(loadApplication)
async function submit(){if(!allowed.value)return window.alert('当前申请不支持延期。');if(!originalTime.value)return window.alert('原预计成果提交时间缺失，无法申请延期。');if(!form.newTime)return window.alert('请选择新的预计成果提交时间。');if(!extensionType.value)return window.alert('新的预计成果提交时间必须晚于原预计提交时间。');if(!form.reason.trim())return window.alert('请填写延期原因。');try{const result=await submitExtensionRequest(application.value.id,{requested_due_at:`${form.newTime}T23:59:59`,reason:form.reason.trim(),attachment_ids:form.attachmentIds});await loadApplication();window.alert(result?.review_level==='admin'||result?.status==='pending_admin_review'?'特殊延期申请已提交，等待管理员审核。':'普通延期申请已提交，等待指导老师确认。');router.push('/student/hour-progress')}catch(error){window.alert(getApiErrorMessage(error,'延期申请提交失败，请稍后重试'))}}
</script>

<template><main class="page"><div class="content"><template v-if="application"><header><div><p class="eyebrow">S504 · EXTENSION APPLICATION</p><h1>延期申请</h1><p>{{ application.title }} · {{ application.id }}</p></div><StatusTag :status="application.status" /></header><section v-if="!allowed" class="warning">当前申请不支持延期。</section><section class="card"><h2>原申请基本信息</h2><dl class="grid"><div><dt>申请名称</dt><dd>{{ application.title }}</dd></div><div><dt>申请类型</dt><dd>{{ application.applyTypeText }}</dd></div><div><dt>主指导老师</dt><dd>{{ application.mainAdvisor?.name||'--' }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="application.status" /></dd></div><div><dt>原预计成果提交时间</dt><dd>{{ originalTime||'--' }}</dd></div><div><dt>是否已申请延期</dt><dd>{{ application.extensionApplied?'是':'否' }}</dd></div></dl></section><section class="card"><h2>延期信息</h2><div class="field"><label for="new-time">新预计成果提交时间</label><input id="new-time" v-model="form.newTime" type="date" :min="originalTime" :disabled="!allowed" /></div><div class="type-result" :class="extensionType||'unknown'"><strong>系统判断：{{ extensionType==='normal'?'普通延期':extensionType==='special'?'特殊延期':'请选择有效的新预计提交时间' }}</strong><p v-if="extensionType">延期 {{ extensionDays }} 天。30 天以内为普通延期，由指导老师确认；超过 30 天为特殊延期，由管理员审核。</p></div><div class="field"><label for="reason">延期原因</label><textarea id="reason" v-model="form.reason" rows="6" :disabled="!allowed" placeholder="请说明无法按期补交成果的原因。"></textarea></div></section><section class="card"><h2>延期证明材料</h2><AttachmentNotice title="延期证明材料" description="可选择能够说明延期原因的证明文件，文件将上传并保存到后端。" :required="false" :accept-types="['PDF','Word','图片']" /><input type="file" multiple :disabled="!allowed" @change="selectFiles" /><div class="files"><article v-for="file in form.files" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size }} · {{ file.uploadedAt }}</small></div><div><button type="button" @click="preview(file)">预览</button><button type="button" @click="download(file)">下载</button><button type="button" class="delete" @click="removeFile(file.id)">删除</button></div></article></div></section><div class="actions"><button type="button" @click="back">返回</button><button type="button" class="submit" :disabled="!allowed" @click="submit">提交延期申请</button></div></template><section v-else class="card empty">申请不存在或不属于当前学生。<button type="button" @click="back">返回</button></section></div></main></template>

<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,920px);margin:auto}header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p{color:#64748b}.warning{margin-bottom:18px;padding:15px;border-radius:10px;color:#b91c1c;background:#fee2e2}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}dt{color:#64748b;font-size:13px}dd{margin:5px 0 0;font-weight:600}.field{display:grid;gap:7px;margin-bottom:18px}.field label{font-weight:700}.field input,.field textarea,input[type=file]{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.type-result{margin-bottom:18px;padding:14px;border-radius:9px;background:#f1f5f9}.type-result p{margin:6px 0 0;color:#475569}.type-result.normal{color:#1d4ed8;background:#eff6ff}.type-result.special{color:#b45309;background:#fffbeb}input[type=file]{margin-top:16px}.files{display:grid;gap:10px;margin-top:14px}.files article{display:flex;justify-content:space-between;gap:14px;padding:13px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.files small{display:block;margin-top:5px;color:#64748b}.files article>div:last-child{display:flex;gap:8px}.files button,.actions button,.empty button{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff;font:inherit;font-weight:700}.files .delete{color:#b91c1c;border-color:#fecaca}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button{padding:10px 18px}.actions .submit{border:0;color:#fff;background:#2563eb}.actions button:disabled{opacity:.5}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}header,.files article{flex-direction:column}.grid{grid-template-columns:1fr}.actions{flex-wrap:wrap}}</style>
