<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getStudentAppeals } from '../api/appealApi.js'
import { adaptAppealList } from '../adapters/appealAdapter.js'
const keyword = ref(''); const status = ref(''); const statuses = ['pending_admin_review','appeal_accepted','processing','completed','appeal_rejected']; const remoteItems=ref([])
onMounted(async()=>{try{remoteItems.value=adaptAppealList(await getStudentAppeals({page_size:100}))}catch(error){window.alert(error?.message||'申诉记录加载失败')}})
const items = computed(() => { const search = keyword.value.trim().toLowerCase(); return remoteItems.value.filter((item) => (!status.value || item.status === status.value) && (!search || item.applicationTitle.toLowerCase().includes(search))).sort((a, b) => String(b.submitTime).localeCompare(String(a.submitTime))) })
function statusText() { return '' }
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">S702 · MY APPEALS</p><h1>我的申诉</h1><p>查看申诉处理状态和最终结果。</p></div><RouterLink class="back" to="/student/feedback">返回问题反馈</RouterLink></header><section class="filters"><label><span>申请名称</span><input v-model="keyword" placeholder="搜索关联申请名称" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option v-for="value in statuses" :key="value" :value="value">{{ value }}</option></select></label></section><section class="panel"><div class="head"><h2>申诉记录</h2><span>共 {{ items.length }} 项</span></div><div class="table"><table><thead><tr><th>申诉编号</th><th>关联申请名称</th><th>提交时间</th><th>当前状态</th><th>管理员处理结果</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.appealId"><td>{{ item.appealId }}</td><td>{{ item.applicationTitle }}</td><td>{{ item.submitTime }}</td><td><StatusTag :status="item.status" :text="statusText(item)" /></td><td>{{ item.finalAdminComment || item.adminComment || '待处理' }}</td><td><RouterLink :to="`/student/appeals/${item.appealId}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="6" class="empty">暂无申诉记录</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1120px);margin:auto}header,.head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800}.back,td a{color:#2563eb;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:1fr 300px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.head{padding:18px 20px}.head h2{margin:0}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left}th{background:#f8fafc}.empty{text-align:center;color:#64748b}@media(max-width:650px){.filters{grid-template-columns:1fr}}</style>
