<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { TASK_STATUS, getTaskTypeText } from '../mock/tasks.js'
import { getAdvisorTasks } from '../api/taskApi.js'
import { adaptTaskList } from '../adapters/taskAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const keyword=ref(''); const selectedStatus=ref(''); const version=ref(0);const remoteItems=ref([])
onMounted(async()=>{try{remoteItems.value=adaptTaskList(await getAdvisorTasks({page_size:100}))}catch(error){window.alert(getApiErrorMessage(error,'任务列表加载失败'))}})
const items=computed(()=>{version.value;const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter(item=>(!selectedStatus.value||item.status===selectedStatus.value)&&(!search||item.title.toLowerCase().includes(search))).sort((a,b)=>String(b.submitTime).localeCompare(String(a.submitTime)))})
const canEdit=(item)=>[TASK_STATUS.DRAFT,TASK_STATUS.PUBLISH_REJECTED].includes(item.status)
function resubmit(){window.alert('请新建发布申请；当前 V1 未提供已驳回任务编辑重提接口。')}
</script>
<template><main class="page"><div class="content"><header class="header"><div><p class="eyebrow">T201 · TASK PUBLISH MANAGEMENT</p><h1>发布任务管理</h1><p>管理本人创建的任务及其发布确认进度。</p></div><div class="header-actions"><RouterLink class="secondary" to="/teacher/dashboard">返回首页</RouterLink><RouterLink class="primary" to="/teacher/publish-task/new">发布新任务</RouterLink></div></header>
<section class="filters"><label><span>任务名称</span><input v-model="keyword" type="search" placeholder="搜索任务名称" /></label><label><span>发布状态</span><select v-model="selectedStatus"><option value="">全部状态</option><option :value="TASK_STATUS.DRAFT">草稿</option><option :value="TASK_STATUS.PENDING_ADMIN_PUBLISH">待管理员确认发布</option><option :value="TASK_STATUS.PUBLISHED">已发布</option><option :value="TASK_STATUS.PUBLISH_REJECTED">发布被驳回</option></select></label></section>
<section class="panel"><div class="panel-head"><h2>我发布的任务</h2><span>共 {{ items.length }} 条</span></div><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>任务类型</th><th>报名截止时间</th><th>当前发布状态</th><th>提交时间</th><th>管理员处理意见</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.taskId"><td><strong>{{ item.title||'未命名任务' }}</strong><small>{{ item.taskId }}</small></td><td>{{ getTaskTypeText(item.taskType) }}</td><td>{{ item.registrationDeadline||'--' }}</td><td><StatusTag :status="item.status" /></td><td>{{ item.submitTime||'--' }}</td><td class="comment">{{ item.adminComment||'--' }}</td><td><div class="row-actions"><RouterLink :to="`/teacher/publish-task/${item.taskId}`">查看详情</RouterLink><RouterLink v-if="canEdit(item)" :to="`/teacher/publish-task/${item.taskId}/edit`">继续编辑</RouterLink><button v-if="item.status===TASK_STATUS.PUBLISH_REJECTED" @click="resubmit(item)">重新提交</button></div></td></tr><tr v-if="!items.length"><td class="empty" colspan="7">暂无符合条件的任务。</td></tr></tbody></table></div></section>
</div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1280px);margin:auto}.header,.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.header{margin-bottom:20px}.header h1{margin:0 0 8px}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.header-actions,.row-actions{display:flex;gap:10px}.secondary,.primary,.row-actions a,.row-actions button{font-weight:700;text-decoration:none}.secondary,.primary{padding:10px 15px;border-radius:9px}.secondary{border:1px solid #cbd5e1;color:#334155;background:#fff}.primary{color:#fff;background:#2563eb}.filters{display:grid;grid-template-columns:1fr 300px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc;font-size:13px}td small{display:block;margin-top:4px;color:#94a3b8}.comment{max-width:250px;overflow:hidden;text-overflow:ellipsis}.row-actions a,.row-actions button{padding:0;border:0;color:#2563eb;background:none;font:inherit;cursor:pointer}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:700px){.page{padding:24px 14px}.header{flex-direction:column}.header-actions,.row-actions{flex-wrap:wrap}.filters{grid-template-columns:1fr}}</style>
