<script setup>
import { computed } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getApplications } from '../mock/applications.js'
import { getAdvisorProcessedExchanges } from '../mock/exchanges.js'
const currentAdvisorId='T001'
const records=computed(()=>[
  ...getApplications().filter(item=>item.mainAdvisor?.id===currentAdvisorId&&item.advisorConfirmTime).map(item=>({id:item.id,title:item.title,type:'课时申请确认',student:item.studentName,time:item.advisorConfirmTime,status:item.advisorStatus,to:`/teacher/confirm/${item.id}`})),
  ...getAdvisorProcessedExchanges(currentAdvisorId).map(item=>({id:item.id,title:item.projectTitle,type:'学分兑换确认',student:item.captainName||item.studentName,time:item.advisorConfirmTime,status:item.advisorConfirmStatus,to:`/teacher/confirm/exchanges/${item.id}`})),
].sort((a,b)=>String(b.time).localeCompare(String(a.time))))
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">PROCESSING RECORDS</p><h1>我的处理记录</h1><p>查看已处理的课时申请与学分兑换确认记录。</p></div><RouterLink class="back" to="/teacher/dashboard">返回教师首页</RouterLink></header><section class="panel"><div class="panel-head"><h2>处理记录</h2><span>共 {{ records.length }} 条</span></div><div class="table-wrap"><table><thead><tr><th>事项编号</th><th>事项名称</th><th>确认类型</th><th>申请学生 / 队长</th><th>处理时间</th><th>处理结果</th><th>操作</th></tr></thead><tbody><tr v-for="item in records" :key="item.id"><td>{{ item.id }}</td><td>{{ item.title }}</td><td>{{ item.type }}</td><td>{{ item.student }}</td><td>{{ item.time }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink class="detail" :to="item.to">查看详情</RouterLink></td></tr><tr v-if="!records.length"><td class="empty" colspan="7">暂无处理记录。</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1120px);margin:auto}header,.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}header{margin-bottom:22px}h1{margin:0 0 8px}header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.back,.detail{color:#2563eb;font-weight:700;text-decoration:none}.back{padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}header{flex-direction:column}}</style>
