<script setup>
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AttachmentNotice from '../components/AttachmentNotice.vue'
import { TASK_STATUS, TASK_TYPE_OPTIONS, getTask, saveTaskDraft, submitTaskForPublish } from '../mock/tasks.js'
const route=useRoute();const router=useRouter();const currentAdvisor={id:'T001',name:'张明'};const existing=route.params.id?getTask(route.params.id):null
const editable=!route.params.id||Boolean(existing&&[TASK_STATUS.DRAFT,TASK_STATUS.PUBLISH_REJECTED].includes(existing.status))
const form=reactive({taskId:existing?.taskId||'',title:existing?.title||'',taskType:existing?.taskType||'',description:existing?.description||'',requirement:existing?.requirement||'',registrationDeadline:(existing?.registrationDeadline||'').replace(' ','T'),resultRequirement:existing?.resultRequirement||'',attachments:(existing?.attachments||[]).map(file=>({...file}))})
const attachmentInput=ref(null);const feedback=ref('');const pageTitle=computed(()=>existing?'编辑发布任务':'发布新任务')
function nowText(){return new Date().toLocaleString('zh-CN',{hour12:false}).replaceAll('/','-')}
function fallbackFileType(name){const extension=name.split('.').pop()?.toUpperCase();return extension&&extension!==name.toUpperCase()?extension:'未知类型'}
function formatFileSize(bytes){if(bytes>=1024*1024)return`${(bytes/(1024*1024)).toFixed(2)} MB`;if(bytes>=1024)return`${(bytes/1024).toFixed(2)} KB`;return`${bytes} B`}
function selectAttachments(event){const files=Array.from(event.target.files||[]);files.forEach((file,index)=>form.attachments.push({id:`TASK-ATT-${Date.now()}-${index}`,name:file.name,type:file.type||fallbackFileType(file.name),size:formatFileSize(file.size),uploadedAt:nowText(),mockUrl:URL.createObjectURL(file)}));event.target.value=''}
function removeAttachment(id){const file=form.attachments.find(item=>item.id===id);if(file?.mockUrl?.startsWith('blob:'))URL.revokeObjectURL(file.mockUrl);form.attachments=form.attachments.filter(item=>item.id!==id)}
function payload(){return{taskId:form.taskId,title:form.title.trim(),taskType:form.taskType,description:form.description.trim(),requirement:form.requirement.trim(),registrationDeadline:form.registrationDeadline.replace('T',' '),resultRequirement:form.resultRequirement.trim(),attachments:form.attachments.map(file=>({...file})),advisorId:currentAdvisor.id,advisorName:currentAdvisor.name,source:'advisor'}}
function validate(){if(!form.title.trim())return'任务名称必填。';if(!form.taskType)return'任务类型必填。';if(!form.description.trim())return'任务说明必填。';if(!form.resultRequirement.trim())return'成果提交要求必填。';if(!form.registrationDeadline)return'报名截止时间必填。';if(new Date(form.registrationDeadline).getTime()<=Date.now())return'报名截止时间必须晚于当前时间。';return''}
function save(){if(!editable)return;const task=saveTaskDraft(payload());if(!task)return window.alert('当前状态不可保存草稿。');window.alert('草稿保存成功。');router.push('/teacher/publish-task')}
function submit(){if(!editable)return;const error=validate();if(error){feedback.value=error;return window.alert(error)};const task=submitTaskForPublish(payload());if(!task)return window.alert('当前状态不可提交发布申请。');window.alert('发布申请已提交，等待管理员确认。');router.push('/teacher/publish-task')}
function back(){router.push('/teacher/publish-task')}
</script>
<template><main class="page"><div class="content"><header class="header"><div><p class="eyebrow">T202 · PUBLISH TASK</p><h1>{{ pageTitle }}</h1><p>填写任务信息并提交管理员确认发布。</p></div></header><section v-if="!editable" class="notice">当前任务状态不可编辑，请返回任务详情查看。</section><form class="form" @submit.prevent="submit"><section class="card"><h2>任务基本信息</h2><div class="grid"><label><span>任务名称 <b>*</b></span><input v-model="form.title" :disabled="!editable" placeholder="请输入任务名称" /></label><label><span>任务类型 <b>*</b></span><select v-model="form.taskType" :disabled="!editable"><option value="">请选择任务类型</option><option v-for="option in TASK_TYPE_OPTIONS" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label class="wide"><span>任务说明 <b>*</b></span><textarea v-model="form.description" :disabled="!editable" rows="5" placeholder="说明任务背景、工作内容和目标"></textarea></label><label class="wide"><span>报名条件</span><textarea v-model="form.requirement" :disabled="!editable" rows="4" placeholder="填写专业、能力、时间等报名条件"></textarea></label><label><span>报名截止时间 <b>*</b></span><input v-model="form.registrationDeadline" :disabled="!editable" type="datetime-local" /></label><label class="wide"><span>成果提交要求 <b>*</b></span><textarea v-model="form.resultRequirement" :disabled="!editable" rows="5" placeholder="说明成果内容、格式和提交标准"></textarea></label></div></section><section class="card attachment-card"><h2>附件上传</h2><AttachmentNotice title="任务附件上传说明" description="请从本地选择任务说明、成果要求、模板文件或其他辅助材料。当前阶段为 Mock 上传，仅保存文件信息，不会真正上传到服务器。" :required="false" :accept-types="['PDF','Word','Excel','PPT','图片','压缩包']" /><label class="file-picker"><span>选择本地文件</span><input ref="attachmentInput" type="file" multiple :disabled="!editable" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg,.zip,.rar" @change="selectAttachments" /><small>支持一次选择多个文件，附件为选填项。</small></label><div class="attachment-list"><article v-for="file in form.attachments" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type||'未知类型' }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><button type="button" :disabled="!editable" @click="removeAttachment(file.id)">删除</button></article><p v-if="!form.attachments.length" class="attachment-empty">暂未选择附件。</p></div></section><p v-if="feedback" class="feedback">{{ feedback }}</p><div class="actions"><button type="button" class="secondary" @click="back">返回</button><button type="button" class="secondary" :disabled="!editable" @click="save">保存草稿</button><button type="submit" class="primary" :disabled="!editable">提交发布申请</button></div></form></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,980px);margin:auto}.header{margin-bottom:22px}.header h1{margin:0 0 8px}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.notice,.feedback{margin-bottom:18px;padding:14px;border-radius:10px;color:#b91c1c;background:#fef2f2}.form{display:grid;gap:20px}.card{padding:24px;border:1px solid #e2e8f0;border-radius:15px;background:#fff}.card h2{margin:0 0 20px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.wide{grid-column:1/-1}label span{display:block;margin-bottom:8px;font-weight:700}label b{color:#dc2626}input,select,textarea{width:100%;padding:11px 12px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;font:inherit}textarea{resize:vertical}.file-picker{display:block;margin-top:18px}.file-picker input{padding:9px}.file-picker small{display:block;margin-top:7px;color:#64748b}.attachment-list{display:grid;gap:10px;margin-top:16px}.attachment-list article{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.attachment-list small{display:block;margin-top:5px;color:#64748b}.attachment-list button{padding:7px 12px;border:1px solid #fecaca;border-radius:8px;color:#b91c1c;background:#fff;font:inherit;font-weight:700;cursor:pointer}.attachment-empty{margin:0;padding:18px;color:#64748b;text-align:center}.actions{display:flex;justify-content:flex-end;gap:12px}.actions button{padding:10px 18px;border-radius:9px;font:inherit;font-weight:700;cursor:pointer}.secondary{border:1px solid #cbd5e1;background:#fff}.primary{border:0;color:#fff;background:#2563eb}button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:650px){.page{padding:24px 14px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.attachment-list article{align-items:flex-start;flex-direction:column}.actions{flex-wrap:wrap}}</style>
