<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getOperationRecord, getOperationRecords } from '../api/recordApi.js'
import { adaptRecordEnvelope, adaptRecordList } from '../adapters/recordAdapter.js'

const type = ref(''); const result = ref(''); const keyword = ref(''); const selected = ref(null)
const allRecords = ref([])
const typeOptions = ['课时申请确认', '无成果申请首次确认', '补交成果确认', '普通延期确认', '学分兑换确认', '任务成果确认', '报名筛选', '队长指定', '发布任务申请']
const resultText = (value) => ({ approved: '通过', confirmed: '通过', rejected: '驳回', submitted: '已提交', completed: '已完成' }[value] || value || '--')
const resultOptions = computed(() => [...new Set(allRecords.value.map((item) => resultText(item.result)))])
const records = computed(() => { const search = keyword.value.trim().toLowerCase(); return allRecords.value.filter((item) => (!type.value || item.type === type.value) && (!result.value || resultText(item.result) === result.value) && (!search || [item.title, item.person, item.sourceId].some((value) => String(value || '').toLowerCase().includes(search)))) })
async function openDetail(item) { try { selected.value = adaptRecordEnvelope(await getOperationRecord(item.id)) } catch (error) { window.alert(error?.message || '处理记录详情加载失败') } }
onMounted(async () => { try { allRecords.value = adaptRecordList(await getOperationRecords({ role_scope: 'advisor', page: 1, page_size: 100 })) } catch (error) { window.alert(error?.message || '处理记录加载失败') } })
</script>

<template><main class="page"><div class="content"><header><div><p class="eyebrow">PROCESSING RECORDS</p><h1>我的处理记录</h1><p>汇总当前指导老师已经处理或提交的业务事项。</p></div><RouterLink class="back" to="/teacher/dashboard">返回指导老师首页</RouterLink></header>
<section class="filters"><label><span>处理类型</span><select v-model="type"><option value="">全部类型</option><option v-for="item in typeOptions" :key="item">{{ item }}</option></select></label><label><span>处理结果</span><select v-model="result"><option value="">全部结果</option><option v-for="item in resultOptions" :key="item">{{ item }}</option></select></label><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名、任务名称或申请名称" /></label></section>
<section class="panel"><div class="panel-head"><h2>处理记录</h2><span>共 {{ records.length }} 条</span></div><div class="table-wrap"><table><thead><tr><th>记录编号</th><th>处理类型</th><th>关联对象名称</th><th>学生 / 队长 / 任务发布人</th><th>处理结果</th><th>处理意见</th><th>处理时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in records" :key="item.id"><td>{{ item.id }}</td><td>{{ item.type }}</td><td>{{ item.title }}</td><td>{{ item.person }}</td><td>{{ resultText(item.result) }}</td><td class="comment">{{ item.comment || '--' }}</td><td>{{ item.time }}</td><td><StatusTag :status="item.status" /></td><td><button class="detail" @click="openDetail(item)">查看详情</button></td></tr><tr v-if="!records.length"><td class="empty" colspan="9">暂无处理记录</td></tr></tbody></table></div></section>
<div v-if="selected" class="modal-mask" @click.self="selected = null"><section class="modal"><header><div><p class="eyebrow">RECORD DETAIL</p><h2>处理记录详情</h2></div><button @click="selected = null">关闭</button></header><dl class="detail-grid"><div><dt>记录编号</dt><dd>{{ selected.id }}</dd></div><div><dt>处理类型</dt><dd>{{ selected.type }}</dd></div><div><dt>关联对象</dt><dd>{{ selected.title }}</dd></div><div><dt>学生 / 队长</dt><dd>{{ selected.person }}</dd></div><div><dt>处理结果</dt><dd>{{ resultText(selected.result) }}</dd></div><div><dt>处理时间</dt><dd>{{ selected.time }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="selected.status" /></dd></div><div class="wide"><dt>处理意见</dt><dd>{{ selected.comment || '--' }}</dd></div><div v-for="(value, label) in selected.detail" :key="label"><dt>{{ label }}</dt><dd>{{ value || '--' }}</dd></div></dl><div class="modal-actions"><button @click="selected = null">返回</button></div></section></div>
</div></main></template>

<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1320px);margin:auto}header,.panel-head,.modal header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}header{margin-bottom:22px}h1{margin:0 0 8px}header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.back{padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;color:#2563eb;background:#fff;font-weight:700;text-decoration:none}.filters{display:grid;grid-template-columns:240px 220px 1fr;gap:14px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters select,.filters input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.comment{max-width:240px;overflow:hidden;text-overflow:ellipsis}.detail{border:0;color:#2563eb;background:none;font-weight:700;cursor:pointer}.empty{padding:34px;text-align:center;color:#64748b}.modal-mask{position:fixed;inset:0;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.48);z-index:20}.modal{width:min(100%,760px);max-height:88vh;overflow:auto;padding:24px;border-radius:16px;background:#fff}.modal header{margin-bottom:20px}.modal h2{margin:0}.modal button{padding:8px 13px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.detail-grid .wide{grid-column:1/-1}dt{color:#64748b}dd{margin:5px 0 0;font-weight:600}.modal-actions{margin-top:24px;text-align:right}@media(max-width:720px){.page{padding:24px 14px}.filters,.detail-grid{grid-template-columns:1fr}.detail-grid .wide{grid-column:auto}header{flex-direction:column}}</style>
