<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getPendingMaterials } from '../api/applicationApi.js'
import { adaptApplicationList } from '../adapters/applicationAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const keyword=ref('');const remoteItems=ref([])
async function loadItems(){try{remoteItems.value=adaptApplicationList(await getPendingMaterials({page_size:100})).items}catch(error){window.alert(getApiErrorMessage(error,'待确认补交成果加载失败'))}}
onMounted(loadItems)
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return remoteItems.value.filter((item)=>item.status==='material_submitted').filter((item)=>!search||[item.studentName,item.title].some((value)=>String(value||'').toLowerCase().includes(search)))})
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">T401 · SUPPLEMENT CONFIRM</p><h1>补交成果确认</h1><p>确认学生针对原课时申请补交的成果材料。</p></div><RouterLink class="back" to="/teacher/confirm">返回待确认事项</RouterLink></header><nav class="tabs"><RouterLink to="/teacher/confirm">课时申请确认</RouterLink><RouterLink class="active" to="/teacher/confirm/supplements">补交成果确认</RouterLink></nav><section class="filter"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或原申请名称" /></label></section><section class="panel"><div class="panel-head"><h2>待再次确认成果</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrap"><table><thead><tr><th>学生姓名</th><th>原申请名称</th><th>申请类型</th><th>补交时间</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.studentName }}</td><td><strong>{{ item.title }}</strong><small>{{ item.id }}</small></td><td>{{ item.applyTypeText }}</td><td>{{ item.supplementTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink class="detail" :to="`/teacher/confirm/supplements/${item.id}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="6" class="empty">暂无待确认的补交成果</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1120px);margin:auto}header,.panel-head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p,.panel-head span{color:#64748b}.back,.detail{color:#2563eb;font-weight:700;text-decoration:none}.back{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.tabs{display:flex;gap:8px;margin-bottom:18px;padding:6px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.tabs a{padding:10px 16px;border-radius:8px;color:#475569;text-decoration:none;font-weight:700}.tabs .active{color:#1d4ed8;background:#dbeafe}.filter{margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filter span{display:block;margin-bottom:7px;font-weight:700}.filter input{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{padding:18px 20px}.panel-head h2{margin:0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px 14px;border-top:1px solid #e2e8f0;text-align:left}th{background:#f8fafc}td small{display:block;margin-top:4px;color:#94a3b8}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:680px){.page{padding:24px 14px}header{flex-direction:column}.tabs{overflow-x:auto}}</style>
