<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { approveApplicationMaterials, getApplicationMaterials, rejectApplicationMaterials } from '../api/applicationApi.js'
import { downloadAttachment, previewAttachment } from '../api/fileApi.js'
import { adaptApplicationEnvelope } from '../adapters/applicationAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const route=useRoute();const router=useRouter();const comment=ref('');const item=ref(null)
const canApprove=computed(()=>item.value?.actions?.can_approve===true||(item.value?.canOperate===true&&item.value?.status==='material_submitted'))
const canReject=computed(()=>item.value?.actions?.can_reject===true||(item.value?.canOperate===true&&item.value?.status==='material_submitted'))
const pending=computed(()=>canApprove.value||canReject.value)
async function loadItem(){try{item.value=adaptApplicationEnvelope(await getApplicationMaterials(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'补交成果详情加载失败'))}}
onMounted(loadItem)
function back(){router.push('/teacher/confirm/supplements')}
async function preview(file){await previewAttachment(file)}
async function download(file){await downloadAttachment(file)}
function showError(error,fallback){if(error?.code===40301||error?.status===403)return window.alert('无权限操作该申请');window.alert(getApiErrorMessage(error,fallback))}
async function approve(){if(!canApprove.value)return window.alert('该补交成果不可确认。');try{await approveApplicationMaterials(item.value.id,{comment:comment.value.trim()});await loadItem();window.alert('补交成果确认通过，申请已进入管理员分配审核老师流程。');back()}catch(error){showError(error,'确认失败，请稍后重试')}}
async function reject(){if(!canReject.value)return window.alert('该补交成果不可驳回。');if(!comment.value.trim())return window.alert('驳回补交成果时必须填写确认意见。');try{await rejectApplicationMaterials(item.value.id,{comment:comment.value.trim()});await loadItem();window.alert('补交成果已驳回，学生可根据意见重新补交。');back()}catch(error){showError(error,'驳回失败，请稍后重试')}}
</script>
<template><main class="page"><div class="content"><template v-if="item"><header><div><p class="eyebrow">T402 · SUPPLEMENT DETAIL</p><h1>补交成果确认详情</h1><p>{{ item.id }}</p></div><StatusTag :status="item.status" /></header><section class="card"><h2>原申请信息</h2><dl class="grid"><div><dt>原申请名称</dt><dd>{{ item.title }}</dd></div><div><dt>申请类型</dt><dd>{{ item.applyTypeText }}</dd></div><div><dt>学生姓名</dt><dd>{{ item.studentName }}</dd></div><div><dt>学号</dt><dd>{{ item.studentId }}</dd></div><div><dt>原预计提交时间</dt><dd>{{ item.expectedResultDate||'--' }}</dd></div><div><dt>实际补交时间</dt><dd>{{ item.supplementTime }}</dd></div><div><dt>当前状态</dt><dd><StatusTag :status="item.status" /></dd></div><div><dt>主指导老师</dt><dd>{{ item.mainAdvisor?.name||'--' }}</dd></div></dl></section><section class="card"><h2>补交成果说明</h2><p class="description">{{ item.resultDescription }}</p></section><section class="card"><h2>成果材料</h2><div class="files"><article v-for="file in item.resultMaterials" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><div><button @click="preview(file)">预览</button><button @click="download(file)">下载</button></div></article><p v-if="!item.resultMaterials?.length">暂无附件材料</p></div></section><section class="card"><h2>证明材料</h2><div class="files"><article v-for="file in item.proofMaterials" :key="file.id"><div><strong>{{ file.name }}</strong><small>{{ file.type }} · {{ file.size||'--' }} · {{ file.uploadedAt||'--' }}</small></div><div><button @click="preview(file)">预览</button><button @click="download(file)">下载</button></div></article><p v-if="!item.proofMaterials?.length">暂无附件材料</p></div></section><section class="card"><h2>指导老师再次确认意见</h2><textarea v-model="comment" rows="5" :disabled="!pending" placeholder="请输入确认意见；驳回时必填。"></textarea></section><div class="actions"><button @click="back">返回</button><button class="reject" :disabled="!pending" @click="reject">驳回补交成果</button><button class="approve" :disabled="!pending" @click="approve">确认通过</button></div></template><section v-else class="card empty">申请不存在或不属于当前指导老师。<button @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,960px);margin:auto}header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p{color:#64748b}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}dt{color:#64748b;font-size:13px}dd{margin:5px 0 0;font-weight:600}.description{white-space:pre-wrap;line-height:1.8}.files{display:grid;gap:10px}.files article{display:flex;justify-content:space-between;gap:14px;padding:13px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.files small{display:block;margin-top:5px;color:#64748b}.files article>div:last-child{display:flex;gap:8px}.files button,.actions button,.empty button{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#2563eb;background:#fff;font:inherit;font-weight:700}textarea{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.actions{display:flex;justify-content:flex-end;gap:10px}.actions button{padding:10px 18px}.actions .reject{color:#b91c1c;border-color:#fecaca}.actions .approve{border:0;color:#fff;background:#2563eb}.actions button:disabled{opacity:.5}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}header,.files article{flex-direction:column}.grid{grid-template-columns:1fr}.actions{flex-wrap:wrap}}</style>
