<script setup>
import { computed, onMounted, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { getTaskTypeText } from '../mock/tasks.js'
import { getAdvisorTasks } from '../api/taskApi.js';import { adaptTaskList } from '../adapters/taskAdapter.js';import { getApiErrorMessage } from '../utils/apiFeedback.js'
const remoteTasks=ref([]);onMounted(async()=>{try{remoteTasks.value=adaptTaskList(await getAdvisorTasks({page_size:100}))}catch(error){window.alert(getApiErrorMessage(error,'我的任务加载失败'))}});const tasks=computed(()=>remoteTasks.value.sort((a,b)=>String(b.submitTime).localeCompare(String(a.submitTime))));const canViewApplicants=(task)=>['published','registration_open','registration_closed','selection_pending','leader_pending','task_in_progress','result_submitted','result_approved','completed'].includes(task.status);const canSelect=(task)=>task.status==='selection_pending'
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">T101 · MY TASKS</p><h1>我的任务</h1><p>查看本人负责的任务及报名情况。</p></div><RouterLink class="back" to="/teacher/dashboard">返回首页</RouterLink></header><section class="panel"><div class="panel-head"><h2>负责的任务</h2><span>共 {{ tasks.length }} 个</span></div><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>任务类型</th><th>当前状态</th><th>报名人数</th><th>已选中人数</th><th>队长</th><th>操作</th></tr></thead><tbody><tr v-for="task in tasks" :key="task.taskId"><td><strong>{{ task.title }}</strong><small>{{ task.taskId }}</small></td><td>{{ getTaskTypeText(task.taskType) }}</td><td><StatusTag :status="task.status" /></td><td>{{ task.applicants?.length||0 }}</td><td>{{ task.selectedStudents?.length||0 }}</td><td>{{ task.leaderName||'--' }}</td><td><div class="row-actions"><RouterLink class="detail" :to="`/teacher/tasks/${task.taskId}`">查看详情</RouterLink><RouterLink v-if="canViewApplicants(task)" class="detail" :to="`/teacher/tasks/${task.taskId}/applicants`">查看报名学生</RouterLink><RouterLink v-if="canSelect(task)" class="detail" :to="`/teacher/tasks/${task.taskId}/applicants/select`">筛选学生</RouterLink><RouterLink v-if="['leader_pending','task_in_progress'].includes(task.status)" class="detail" :to="`/teacher/tasks/${task.taskId}/leader`">指定队长</RouterLink></div></td></tr><tr v-if="!tasks.length"><td class="empty" colspan="7">暂无任务</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1240px);margin:auto}header,.panel-head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:22px}h1{margin:0 0 8px}header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.back,.detail{color:#2563eb;font-weight:700;text-decoration:none}.back{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{align-items:center;padding:18px 20px}.panel-head h2{margin:0}.panel-head span{color:#64748b}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}td small{display:block;margin-top:4px;color:#94a3b8}.row-actions{display:flex;gap:10px}.empty{text-align:center;color:#64748b}@media(max-width:650px){.page{padding:24px 14px}header{flex-direction:column}.row-actions{flex-wrap:wrap}}</style>
