<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import StatusTag from '../components/StatusTag.vue'
import { TASK_STATUS, getTaskTypeText } from '../mock/tasks.js'
import { getAdvisorTask } from '../api/taskApi.js'
import { adaptTaskEnvelope } from '../adapters/taskAdapter.js'
import { getApiErrorMessage } from '../utils/apiFeedback.js'
const route=useRoute();const router=useRouter();const task=ref(null)
onMounted(async()=>{try{task.value=adaptTaskEnvelope(await getAdvisorTask(Number(route.params.id)))}catch(error){window.alert(getApiErrorMessage(error,'任务详情加载失败'))}})
function back(){router.push('/teacher/publish-task')}
function previewFile(){window.alert('当前为 Mock 附件预览，真实预览需后端文件服务支持。')}
function downloadFile(){window.alert('当前为 Mock 附件下载，真实下载需后端文件服务支持。')}
function applicants(){window.alert('报名学生入口已预留，报名与筛选功能将在后续模块开发。')}
</script>
<template><main class="page"><div class="content"><template v-if="task"><header class="header"><div><p class="eyebrow">T203 · TASK DETAIL</p><h1>{{ task.title||'未命名任务' }}</h1><p>{{ task.taskId }}</p></div><StatusTag :status="task.status" /></header>
<section v-if="task.status===TASK_STATUS.PUBLISH_REJECTED" class="rejected"><strong>发布申请被管理员驳回</strong><p>{{ task.adminComment||'管理员未填写处理意见。' }}</p></section>
<section class="card"><h2>任务基本信息</h2><dl class="grid"><div><dt>任务名称</dt><dd>{{ task.title||'--' }}</dd></div><div><dt>任务类型</dt><dd>{{ getTaskTypeText(task.taskType) }}</dd></div><div class="wide"><dt>任务说明</dt><dd>{{ task.description||'--' }}</dd></div><div class="wide"><dt>报名条件</dt><dd>{{ task.requirement||'不限' }}</dd></div><div><dt>报名截止时间</dt><dd>{{ task.registrationDeadline||'--' }}</dd></div><div><dt>提交发布时间</dt><dd>{{ task.submitTime||'--' }}</dd></div><div><dt>正式发布时间</dt><dd>{{ task.publishTime||'--' }}</dd></div><div><dt>当前发布状态</dt><dd><StatusTag :status="task.status" /></dd></div></dl></section>
<section class="card"><h2>发布人信息</h2><dl class="grid"><div><dt>指导老师</dt><dd>{{ task.advisorName }}</dd></div><div><dt>指导老师编号</dt><dd>{{ task.advisorId }}</dd></div><div><dt>任务来源</dt><dd>{{ task.source==='advisor'?'指导老师发布':'管理员发布' }}</dd></div></dl></section>
<section class="card"><h2>成果提交要求</h2><p class="text">{{ task.resultRequirement||'--' }}</p></section>
<section class="card"><h2>附件材料</h2><div class="files"><article v-for="file in task.attachments" :key="file.id||file.name"><div class="file-info"><strong>{{ file.name }}</strong><small>文件类型：{{ file.type||'未知类型' }} · 文件大小：{{ file.size||'--' }} · 上传时间：{{ file.uploadedAt||'--' }}</small></div><div><button @click="previewFile(file)">预览</button><button @click="downloadFile">下载</button></div></article><p v-if="!task.attachments?.length" class="empty">暂无附件材料。</p></div></section>
<section class="card"><h2>管理员确认结果</h2><dl class="grid"><div><dt>确认意见</dt><dd>{{ task.adminComment||'--' }}</dd></div><div><dt>确认时间</dt><dd>{{ task.adminConfirmTime||'--' }}</dd></div></dl></section>
<section class="card"><h2>报名情况</h2><p>当前报名 {{ task.applicants?.length||0 }} 人，已选中 {{ task.selectedStudents?.length||0 }} 人。</p><button v-if="task.status===TASK_STATUS.PUBLISHED" class="outline" @click="applicants">查看报名学生</button><p v-else class="muted">任务正式发布后可进入报名学生页面。</p></section>
<div class="actions"><button class="secondary" @click="back">返回</button><RouterLink v-if="task.status===TASK_STATUS.PUBLISH_REJECTED" class="primary" :to="`/teacher/publish-task/${task.taskId}/edit`">修改后重新提交</RouterLink></div>
</template><section v-else class="card empty"><h1>未找到任务</h1><button class="secondary" @click="back">返回</button></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,980px);margin:auto}.header{display:flex;justify-content:space-between;gap:20px;margin-bottom:20px}.header h1{margin:0}.header p{color:#64748b}.eyebrow{margin:0 0 6px;color:#2563eb!important;font-size:12px;font-weight:800;letter-spacing:.12em}.rejected{margin-bottom:18px;padding:18px;border-radius:12px;color:#b91c1c;background:#fee2e2}.rejected p{margin:7px 0 0}.card{margin-bottom:18px;padding:22px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.card h2{margin:0 0 18px;font-size:19px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin:0}.wide{grid-column:1/-1}.grid dt{color:#64748b;font-size:13px}.grid dd{margin:5px 0 0;font-weight:600;line-height:1.7}.text{line-height:1.8}.files{display:grid;gap:10px}.files article{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:14px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.files article>div:last-child{display:flex;gap:8px}.file-info small{display:block;margin-top:5px;color:#64748b}.files button,.outline{padding:8px 11px;border:1px solid #bfdbfe;border-radius:8px;color:#1d4ed8;background:#fff;font-weight:700;cursor:pointer}.muted,.empty{color:#64748b}.actions{display:flex;justify-content:flex-end;gap:10px}.secondary,.primary{padding:10px 18px;border-radius:9px;font-weight:700;text-decoration:none;cursor:pointer}.secondary{border:1px solid #cbd5e1;background:#fff}.primary{border:0;color:#fff;background:#2563eb}.empty{text-align:center}@media(max-width:650px){.page{padding:24px 14px}.header,.files article{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.actions{flex-wrap:wrap}}</style>
