<script setup>
import { computed, ref } from 'vue'
import StatusTag from '../components/StatusTag.vue'
import { APPLICATION_STATUS, getAdvisorPendingNormalExtensions } from '../mock/applications.js'
const advisorId='T001';const keyword=ref('');const status=ref(APPLICATION_STATUS.PENDING_ADVISOR_EXTENSION)
const items=computed(()=>{const search=keyword.value.trim().toLowerCase();return getAdvisorPendingNormalExtensions(advisorId).filter((item)=>(!status.value||item.status===status.value)&&(!search||[item.studentName,item.title].some((value)=>String(value||'').toLowerCase().includes(search))))})
</script>
<template><main class="page"><div class="content"><header><div><p class="eyebrow">T501 · NORMAL EXTENSION</p><h1>普通延期确认</h1><p>处理当前指导老师负责的普通延期申请。</p></div><RouterLink class="back" to="/teacher/confirm">返回待确认事项</RouterLink></header><nav class="tabs"><RouterLink to="/teacher/confirm">课时申请确认</RouterLink><RouterLink to="/teacher/confirm/supplements">补交成果确认</RouterLink><RouterLink class="active" to="/teacher/confirm/extensions">普通延期确认</RouterLink></nav><section class="filters"><label><span>搜索</span><input v-model="keyword" placeholder="学生姓名或申请名称" /></label><label><span>状态</span><select v-model="status"><option value="">全部</option><option :value="APPLICATION_STATUS.PENDING_ADVISOR_EXTENSION">延期申请待指导老师确认</option></select></label></section><section class="panel"><div class="panel-head"><h2>待确认普通延期</h2><span>共 {{ items.length }} 项</span></div><div class="table-wrap"><table><thead><tr><th>申请编号</th><th>学生姓名</th><th>申请名称</th><th>原预计时间</th><th>新预计时间</th><th>延期原因</th><th>提交时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.id }}</td><td>{{ item.studentName }}</td><td>{{ item.title }}</td><td>{{ item.originalExpectedResultTime }}</td><td>{{ item.newExpectedResultTime }}</td><td class="reason">{{ item.extensionReason }}</td><td>{{ item.extensionSubmitTime }}</td><td><StatusTag :status="item.status" /></td><td><RouterLink class="detail" :to="`/teacher/confirm/extensions/${item.id}`">查看详情</RouterLink></td></tr><tr v-if="!items.length"><td colspan="9" class="empty">暂无待确认普通延期申请</td></tr></tbody></table></div></section></div></main></template>
<style scoped>.page{min-height:100vh;padding:40px 24px;background:#f3f6fb}.content{width:min(100%,1380px);margin:auto}header,.panel-head{display:flex;justify-content:space-between;gap:20px}header{margin-bottom:20px}h1{margin:0}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.12em}header p,.panel-head span{color:#64748b}.back,.detail{color:#2563eb;font-weight:700;text-decoration:none}.back{height:max-content;padding:9px 14px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.tabs{display:flex;gap:8px;margin-bottom:18px;padding:6px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.tabs a{padding:10px 16px;border-radius:8px;color:#475569;text-decoration:none;font-weight:700}.tabs .active{color:#1d4ed8;background:#dbeafe}.filters{display:grid;grid-template-columns:1fr 320px;gap:16px;margin-bottom:18px;padding:18px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.filters span{display:block;margin-bottom:7px;font-weight:700}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit;background:#fff}.panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.panel-head{padding:18px 20px}.panel-head h2{margin:0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-top:1px solid #e2e8f0;text-align:left;white-space:nowrap}th{background:#f8fafc}.reason{max-width:240px;overflow:hidden;text-overflow:ellipsis}.empty{padding:34px;text-align:center;color:#64748b}@media(max-width:680px){.page{padding:24px 14px}header{flex-direction:column}.filters{grid-template-columns:1fr}.tabs{overflow-x:auto}}</style>
