"""teacher specialty and ui support

Revision ID: ac4b6114128d
Revises: ec8b4a632f6c
Create Date: 2026-05-22 10:28:03.213158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4b6114128d'
down_revision = 'ec8b4a632f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('course_name')
        batch_op.drop_column('major_name')

    # ### end Alembic commands ###
