"""align hour application fields

Revision ID: ec8b4a632f6c
Revises: 6aa79d63d11c
Create Date: 2026-05-18 16:19:04.754694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec8b4a632f6c'
down_revision = '6aa79d63d11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hour_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_members', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('major_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('instructor_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('achievement_submission', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hour_applications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
        batch_op.drop_column('achievement_submission')
        batch_op.drop_column('instructor_name')
        batch_op.drop_column('course_name')
        batch_op.drop_column('major_name')
        batch_op.drop_column('participant_members')

    # ### end Alembic commands ###
