import { get, post } from './request.js'

export const saveApplicationDraft = (data) => post('/student/hour-applications/drafts', data)
export const submitApplication = (data) => post('/student/hour-applications', data)
export const getStudentApplications = (params) => get('/student/hour-applications', params)
export const getStudentApplication = (id) => get(`/student/hour-applications/${id}`)
export const getAdminApplications = (params) => get('/admin/hour-applications', params)
export const getAdvisorPendingApplications = (params) => get('/advisor/hour-applications/pending', params)
export const getAdvisorApplication = (id) => get(`/advisor/hour-applications/${id}`)
export const approveApplicationByAdvisor = (id, data = {}) => post(`/advisor/hour-applications/${id}/approve`, data)
export const rejectApplicationByAdvisor = (id, data) => post(`/advisor/hour-applications/${id}/reject`, data)
export const getPendingAssignmentApplications = (params) => get('/admin/hour-applications/pending-assignment', params)
export const getAdminApplication = (id) => get(`/admin/hour-applications/${id}`)
export const assignApplicationReviewer = (id, data) => post(`/admin/hour-applications/${id}/assign-reviewer`, data)
export const getReviewerPendingApplications = (params) => get('/reviewer/hour-applications/pending', params)
export const getReviewerApplication = (id) => get(`/reviewer/hour-applications/${id}`)
export const approveApplicationByReviewer = (id, data = {}) => post(`/reviewer/hour-applications/${id}/approve`, data)
export const modifiedApproveApplication = (id, data) => post(`/reviewer/hour-applications/${id}/modified-approve`, data)
export const rejectApplicationByReviewer = (id, data) => post(`/reviewer/hour-applications/${id}/reject`, data)
export const getPendingFinalApplications = (params) => get('/admin/hour-applications/pending-final', params)
export const getApplicationFinalReview = (id) => get(`/admin/hour-applications/${id}/final-review`)
export const finalApproveApplication = (id, data = {}) => post(`/admin/hour-applications/${id}/final-approve`, data)
export const finalRejectApplication = (id, data) => post(`/admin/hour-applications/${id}/final-reject`, data)
export const submitApplicationMaterials = (id, data) => post(`/student/hour-applications/${id}/materials`, data)
export const getPendingMaterials = (params) => get('/advisor/hour-applications/materials/pending', params)
export const getApplicationMaterials = (id) => get(`/advisor/hour-applications/${id}/materials`)
export const approveApplicationMaterials = (id, data = {}) => post(`/advisor/hour-applications/${id}/materials/approve`, data)
export const rejectApplicationMaterials = (id, data) => post(`/advisor/hour-applications/${id}/materials/reject`, data)
export const submitExtensionRequest = (id, data) => post(`/student/hour-applications/${id}/extension-requests`, data)
export const getAdvisorPendingExtensions = (params) => get('/advisor/extension-requests/pending', params)
export const getExtensionRequest = (id) => get(`/extension-requests/${id}`)
export const approveExtensionByAdvisor = (id, data = {}) => post(`/advisor/extension-requests/${id}/approve`, data)
export const rejectExtensionByAdvisor = (id, data) => post(`/advisor/extension-requests/${id}/reject`, data)
export const getAdminPendingSpecialExtensions = (params) => get('/admin/extension-requests/pending-special', params)
export const approveExtensionByAdmin = (id, data = {}) => post(`/admin/extension-requests/${id}/approve`, data)
export const rejectExtensionByAdmin = (id, data) => post(`/admin/extension-requests/${id}/reject`, data)
export const getAdminExtensions = (params) => get('/admin/extension-requests', params)
export const closeApplication = (id, data = {}) => post(`/admin/hour-applications/${id}/close`, data)

