import { get, patch, post, put } from './request.js'

export const getTaskTypes = (params) => get('/task-types', params)
export const getAdminTaskTypes = (params) => get('/admin/task-types', params)
export const createTaskType = (data) => post('/admin/task-types', data)
export const updateTaskType = (id, data) => put(`/admin/task-types/${id}`, data)
export const patchTaskType = (id, data) => patch(`/admin/task-types/${id}`, data)
export const enableTaskType = (id) => post(`/admin/task-types/${id}/enable`)
export const disableTaskType = (id) => post(`/admin/task-types/${id}/disable`)
export const getAdvisors = (params) => get('/teachers/advisors', params)
export const getReviewers = (params) => get('/admin/reviewers', params)
export const saveAdminTaskDraft = (data) => post('/admin/tasks/drafts', data)
export const publishAdminTask = (data) => post('/admin/tasks', data)
export const saveAdvisorTaskDraft = (data) => post('/advisor/tasks/drafts', data)
export const publishAdvisorTask = (data) => post('/advisor/tasks', data)
export const getStudentTasks = (params) => get('/student/tasks', params)
export const getStudentTask = (id) => get(`/student/tasks/${id}`)
export const registerTask = (id, data = {}) => post(`/student/tasks/${id}/registrations`, data)
export const getMyTasks = (params) => get('/student/my-tasks', params)
export const getTaskRegistration = (id) => get(`/student/task-registrations/${id}`)
export const getTaskRegistrations = (id, params) => get(`/advisor/tasks/${id}/registrations`, params)
export const selectTaskMembers = (id, data) => post(`/advisor/tasks/${id}/registrations/select`, data)
export const getSelectedTaskMembers = (id) => get(`/advisor/tasks/${id}/selected-members`)
export const assignTaskLeader = (id, data) => post(`/advisor/tasks/${id}/leader`, data)
export const getTaskTeam = (id) => get(`/student/tasks/${id}/team`)
export const submitTaskResult = (id, data) => post(`/student/tasks/${id}/result-submissions`, data)
export const resubmitTaskResult = (id, data) => post(`/student/task-result-submissions/${id}/resubmit`, data)
export const getTaskResult = (id) => get(`/advisor/task-result-submissions/${id}`)
export const approveTaskResult = (id, data = {}) => post(`/advisor/task-result-submissions/${id}/approve`, data)
export const rejectTaskResult = (id, data) => post(`/advisor/task-result-submissions/${id}/reject`, data)
export const getAdminTasks = (params) => get('/admin/tasks', params)
export const getAdminTask = (id) => get(`/admin/tasks/${id}`)
export const getAdvisorTasks = (params) => get('/advisor/tasks', params)
export const getAdvisorTask = (id) => get(`/advisor/tasks/${id}`)
export const getTaskPublishRequests = (params) => get('/admin/task-publish-requests', params)
export const getTaskPublishRequest = (id) => get(`/admin/task-publish-requests/${id}`)
export const approveTaskPublish = (id, data = {}) => post(`/admin/task-publish-requests/${id}/approve`, data)
export const rejectTaskPublish = (id, data) => post(`/admin/task-publish-requests/${id}/reject`, data)
